In [1]:
!pip show requests

Name: requests
Version: 2.32.5
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache-2.0
Location: C:\Users\Suba\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: certifi, charset_normalizer, idna, urllib3
Required-by: jupyterlab_server

In [68]:
import json

In [9]:
# scraping live matches data

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/live"

headers = {
	"x-rapidapi-key": "3cdc535360mshc729ab2d422c376p16cacbjsnc90870850ea6",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [10]:
data

{'typeMatches': [{'matchType': 'International',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11542,
      'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
      'matches': [{'matchInfo': {'matchId': 146950,
         'seriesId': 11542,
         'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
         'matchDesc': '2nd Match',
         'matchFormat': 'T20',
         'startDate': '1772001000000',
         'endDate': '1772013600000',
         'state': 'Complete',
         'status': 'Bahrain won by 4 wkts',
         'team1': {'teamId': 555,
          'teamName': 'Bhutan',
          'teamSName': 'BTN',
          'imageId': 172607},
         'team2': {'teamId': 543,
          'teamName': 'Bahrain',
          'teamSName': 'BHR',
          'imageId': 172594},
         'venueInfo': {'id': 474,
          'ground': 'Terdthai Cricket Ground',
          'city': 'Bangkok',
          'timezone': '+07:00',
          'latitude': '13.756331',
          'longitude': '100.501765'},
         'currBatTeamId': 543,
         'seriesStartDt': '1771977600000',
         'seriesEndDt': '1772409600000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 91,
           'wickets': 10,
           'overs': 16.5}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 95,
           'wickets': 6,
           'overs': 17.4}}}},
       {'matchInfo': {'matchId': 146939,
         'seriesId': 11542,
         'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
         'matchDesc': '1st Match',
         'matchFormat': 'T20',
         'startDate': '1771984800000',
         'endDate': '1771997400000',
         'state': 'Complete',
         'status': 'Japan won by 37 runs',
         'team1': {'teamId': 547,
          'teamName': 'Japan',
          'teamSName': 'JPN',
          'imageId': 248418},
         'team2': {'teamId': 384,
          'teamName': 'Thailand',
          'teamSName': 'THAI',
          'imageId': 172437},
         'venueInfo': {'id': 474,
          'ground': 'Terdthai Cricket Ground',
          'city': 'Bangkok',
          'timezone': '+07:00',
          'latitude': '13.756331',
          'longitude': '100.501765'},
         'currBatTeamId': 547,
         'seriesStartDt': '1771977600000',
         'seriesEndDt': '1772409600000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 157,
           'wickets': 6,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 120,
           'wickets': 9,
           'overs': 19.6}}}}]}},
    {'seriesAdWrapper': {'seriesId': 11581,
      'seriesName': 'Kuwait tour of Hong Kong, China, 2026',
      'matches': [{'matchInfo': {'matchId': 147700,
         'seriesId': 11581,
         'seriesName': 'Kuwait tour of Hong Kong, China, 2026',
         'matchDesc': '1st T20I',
         'matchFormat': 'T20',
         'startDate': '1771997400000',
         'endDate': '1772010000000',
         'state': 'Complete',
         'status': 'Hong Kong, China won by 3 wkts',
         'team1': {'teamId': 298,
          'teamName': 'Kuwait',
          'teamSName': 'KUW',
          'imageId': 776312},
         'team2': {'teamId': 8,
          'teamName': 'Hong Kong, China',
          'teamSName': 'HKC',
          'imageId': 776271},
         'venueInfo': {'id': 454,
          'ground': 'Mission Road Ground',
          'city': 'Mong Kok',
          'timezone': '+08:00',
          'latitude': '22.323286',
          'longitude': '114.1828583'},
         'currBatTeamId': 8,
         'seriesStartDt': '1771977600000',
         'seriesEndDt': '1772496000000',
         'isTimeAnnounced': True,
         'stateTitle': 'HKC Won'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 182,
           'wickets': 6,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 186,
           'wickets': 7,
           'overs': 18.5}}}}]}}]},
  {'matchType': 'Domestic',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10317,
      'seriesName': 'Ranji Trophy Elite 2025-26',
      'matches': [{'matchInfo': {'matchId': 125085,
         'seriesId': 10317,
         'seriesName': 'Ranji Trophy Elite 2025-26',
         'matchDesc': 'Final',
         'matchFormat': 'TEST',
         'startDate': '1771905600000',
         'endDate': '1772276400000',
         'state': 'Rain',
         'status': 'Day 2: Bad light stops play',
         'team1': {'teamId': 252,
          'teamName': 'Jammu and Kashmir',
          'teamSName': 'JK',
          'imageId': 172305},
         'team2': {'teamId': 128,
          'teamName': 'Karnataka',
          'teamSName': 'KAR',
          'imageId': 776345},
         'venueInfo': {'id': 329,
          'ground': 'KSCA Hubli Cricket Ground',
          'city': 'Hubli',
          'timezone': '+05:30',
          'latitude': '15.370228',
          'longitude': '75.127888'},
         'currBatTeamId': 252,
         'seriesStartDt': '1760486400000',
         'seriesEndDt': '1772409600000',
         'isTimeAnnounced': True,
         'stateTitle': 'Break'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 527,
           'wickets': 6,
           'overs': 155.6}}}}]}},
    {'seriesAdWrapper': {'seriesId': 11559,
      'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
      'matches': [{'matchInfo': {'matchId': 147170,
         'seriesId': 11559,
         'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
         'matchDesc': '6th Match',
         'matchFormat': 'ODI',
         'startDate': '1772004600000',
         'endDate': '1772033400000',
         'state': 'Toss',
         'status': 'South Western Districts opt to bat',
         'team1': {'teamId': 1768,
          'teamName': 'South Western Districts',
          'teamSName': 'SWD',
          'imageId': 349609},
         'team2': {'teamId': 903,
          'teamName': 'Mpumalanga Rhinos',
          'teamSName': 'MPR',
          'imageId': 248434},
         'venueInfo': {'id': 1193,
          'ground': 'Uplands College, White River',
          'city': 'Mpumalanga',
          'timezone': '+02:00',
          'latitude': '-25.328440',
          'longitude': '31.017780'},
         'seriesStartDt': '1771632000000',
         'seriesEndDt': '1774310400000',
         'isTimeAnnounced': True,
         'stateTitle': 'Toss'}},
       {'matchInfo': {'matchId': 147159,
         'seriesId': 11559,
         'seriesName': 'CSA Provincial One-Day Challenge Division Two 2026',
         'matchDesc': '5th Match',
         'matchFormat': 'ODI',
         'startDate': '1772006400000',
         'endDate': '1772035200000',
         'state': 'Toss',
         'status': 'Eastern Storm opt to bowl',
         'team1': {'teamId': 923,
          'teamName': 'Northern Cape',
          'teamSName': 'NCAPE',
          'imageId': 248438},
         'team2': {'teamId': 933,
          'teamName': 'Eastern Storm',
          'teamSName': 'ESTORM',
          'imageId': 248407},
         'venueInfo': {'id': 148,
          'ground': 'Diamond Oval',
          'city': 'Kimberley',
          'timezone': '+02:00',
          'latitude': '-28.742487',
          'longitude': '24.742101'},
         'seriesStartDt': '1771632000000',
         'seriesEndDt': '1774310400000',
         'isTimeAnnounced': True,
         'stateTitle': 'Toss'}}]}},
    {'ad': {'name': 'native_matches',
      'layout': 'native_large',
      'position': 4}}]},
  {'matchType': 'Women',
   'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10245,
      'seriesName': 'Zimbabwe Women tour of New Zealand, 2026',
      'matches': [{'matchInfo': {'matchId': 122737,
         'seriesId': 10245,
         'seriesName': 'Zimbabwe Women tour of New Zealand, 2026',
         'matchDesc': '1st T20I',
         'matchFormat': 'T20',
         'startDate': '1772000100000',
         'endDate': '1772012700000',
         'state': 'Complete',
         'status': 'New Zealand Women won by 92 runs',
         'team1': {'teamId': 98,
          'teamName': 'New Zealand Women',
          'teamSName': 'NZW',
          'imageId': 776338},
         'team2': {'teamId': 388,
          'teamName': 'Zimbabwe Women',
          'teamSName': 'ZIMW',
          'imageId': 776203},
         'venueInfo': {'id': 100,
          'ground': 'Seddon Park',
          'city': 'Hamilton',
          'timezone': '+13:00',
          'latitude': '-37.786654',
          'longitude': '175.266647'},
         'currBatTeamId': 98,
         'seriesStartDt': '1771977600000',
         'seriesEndDt': '1773360000000',
         'isTimeAnnounced': True,
         'stateTitle': 'Complete'},
        'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
           'runs': 202,
           'wickets': 1,
           'overs': 19.6}},
         'team2Score': {'inngs1': {'inningsId': 2,
           'runs': 110,
           'wickets': 4,
           'overs': 19.6}}}}]}}]}],
 'filters': {'matchType': ['International', 'League', 'Domestic', 'Women']},
 'appIndex': {'seoTitle': 'Live Cricket Score - Scorecard and Match Results',
  'webURL': 'www.cricbuzz.com/live-cricket-scores/'},
 'responseLastUpdated': '1772016083'}

In [11]:
# top level keys
print(data.keys())

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])

In [12]:
type(data)

dict

In [13]:
import pandas as pd

matches_list = []

for type_block in data.get("typeMatches", []):
    match_type = type_block.get("matchType")

    for series_block in type_block.get("seriesMatches", []):
        series = series_block.get("seriesAdWrapper", {})
        series_id = series.get("seriesId")
        series_name = series.get("seriesName")

        for match in series.get("matches", []):
            match_info = match.get("matchInfo", {})
            match_score = match.get("matchScore", {})

            team1 = match_info.get("team1", {})
            team2 = match_info.get("team2", {})
            venue = match_info.get("venueInfo", {})

            team1_score = match_score.get("team1Score", {}).get("inngs1", {})
            team2_score = match_score.get("team2Score", {}).get("inngs1", {})

            matches_list.append({
                "match_id": match_info.get("matchId"),
                "match_type": match_type,
                "series_id": series_id,
                "series_name": series_name,
                "match_desc": match_info.get("matchDesc"),
                "match_format": match_info.get("matchFormat"),
                "state": match_info.get("state"),
                "status": match_info.get("status"),

                "team1_id": team1.get("teamId"),
                "team1_name": team1.get("teamName"),
                "team2_id": team2.get("teamId"),
                "team2_name": team2.get("teamName"),

                "curr_bat_team_id": match_info.get("currBatTeamId"),

                "venue_id": venue.get("id"),
                "ground": venue.get("ground"),
                "city": venue.get("city"),
                "timezone": venue.get("timezone"),

                "start_date": match_info.get("startDate"),
                "end_date": match_info.get("endDate"),

                "team1_runs": team1_score.get("runs"),
                "team1_wickets": team1_score.get("wickets"),
                "team1_overs": team1_score.get("overs"),

                "team2_runs": team2_score.get("runs"),
                "team2_wickets": team2_score.get("wickets"),
                "team2_overs": team2_score.get("overs"),
            })

df_matches = pd.DataFrame(matches_list)

In [14]:
df_matches.head()
df_matches.shape
df_matches.isnull().sum()

match_id            0
match_type          0
series_id           0
series_name         0
match_desc          0
match_format        0
state               0
status              0
team1_id            0
team1_name          0
team2_id            0
team2_name          0
curr_bat_team_id    2
venue_id            0
ground              0
city                0
timezone            0
start_date          0
end_date            0
team1_runs          2
team1_wickets       2
team1_overs         2
team2_runs          3
team2_wickets       3
team2_overs         3
dtype: int64

In [16]:
# Convert Epoch → Timestamp

df_matches["start_date"] = pd.to_datetime(
    df_matches["start_date"].astype("int64"), unit="ms"
)

df_matches["end_date"] = pd.to_datetime(
    df_matches["end_date"].astype("int64"), unit="ms"
)

In [17]:
# Fix Numeric Columns Explicitly

score_cols = [
    "team1_runs", "team1_wickets", "team1_overs",
    "team2_runs", "team2_wickets", "team2_overs"
]

df_matches[score_cols] = df_matches[score_cols].apply(
    pd.to_numeric, errors="coerce"
)

In [18]:
import numpy as np

df_db = df_matches.copy()
df_db = df_db.replace({np.nan: None})
df_db = df_db.where(pd.notnull(df_db), None)

In [19]:
df_db.head()

,match_id,match_type,series_id,series_name,match_desc,match_format,state,status,team1_id,team1_name,...,city,timezone,start_date,end_date,team1_runs,team1_wickets,team1_overs,team2_runs,team2_wickets,team2_overs
0,146950,International,11542,Quadrangular T20I Series in Thailand 2026,2nd Match,T20,Complete,Bahrain won by 4 wkts,555,Bhutan,...,Bangkok,+07:00,2026-02-25 06:30:00,2026-02-25 10:00:00,91.0,10.0,16.5,95.0,6.0,17.4
1,146939,International,11542,Quadrangular T20I Series in Thailand 2026,1st Match,T20,Complete,Japan won by 37 runs,547,Japan,...,Bangkok,+07:00,2026-02-25 02:00:00,2026-02-25 05:30:00,157.0,6.0,19.6,120.0,9.0,19.6
2,147700,International,11581,"Kuwait tour of Hong Kong, China, 2026",1st T20I,T20,Complete,"Hong Kong, China won by 3 wkts",298,Kuwait,...,Mong Kok,+08:00,2026-02-25 05:30:00,2026-02-25 09:00:00,182.0,6.0,19.6,186.0,7.0,18.5
3,125085,Domestic,10317,Ranji Trophy Elite 2025-26,Final,TEST,Rain,Day 2: Bad light stops play,252,Jammu and Kashmir,...,Hubli,+05:30,2026-02-24 04:00:00,2026-02-28 11:00:00,527.0,6.0,155.6,None,None,None
4,147170,Domestic,11559,CSA Provincial One-Day Challenge Division Two ...,6th Match,ODI,Toss,South Western Districts opt to bat,1768,South Western Districts,...,Mpumalanga,+02:00,2026-02-25 07:30:00,2026-02-25 15:30:00,None,None,None,None,None,None

In [20]:
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [21]:
upsert_query = """
INSERT INTO live_matches (
    match_id, match_type, series_id, series_name, match_desc, match_format,
    state, status,
    team1_id, team1_name, team2_id, team2_name, curr_bat_team_id,
    venue_id, ground, city, timezone,
    start_date, end_date,
    team1_runs, team1_wickets, team1_overs,
    team2_runs, team2_wickets, team2_overs,
    last_updated
)
VALUES (
    %(match_id)s, %(match_type)s, %(series_id)s, %(series_name)s, %(match_desc)s, %(match_format)s,
    %(state)s, %(status)s,
    %(team1_id)s, %(team1_name)s, %(team2_id)s, %(team2_name)s, %(curr_bat_team_id)s,
    %(venue_id)s, %(ground)s, %(city)s, %(timezone)s,
    %(start_date)s, %(end_date)s,
    %(team1_runs)s, %(team1_wickets)s, %(team1_overs)s,
    %(team2_runs)s, %(team2_wickets)s, %(team2_overs)s,
    CURRENT_TIMESTAMP
)
ON CONFLICT (match_id)
DO UPDATE SET
    state = EXCLUDED.state,
    status = EXCLUDED.status,
    curr_bat_team_id = EXCLUDED.curr_bat_team_id,
    team1_runs = EXCLUDED.team1_runs,
    team1_wickets = EXCLUDED.team1_wickets,
    team1_overs = EXCLUDED.team1_overs,
    team2_runs = EXCLUDED.team2_runs,
    team2_wickets = EXCLUDED.team2_wickets,
    team2_overs = EXCLUDED.team2_overs,
    last_updated = CURRENT_TIMESTAMP;
"""

In [22]:
conn.rollback()

In [23]:
try:
    for idx, row in df_db.iterrows():
        cursor.execute(upsert_query, row.to_dict())

    conn.commit()
    print("✅ Live match data upserted successfully")

except Exception as e:
    conn.rollback()
    print("❌ Insert failed")
    raise e

✅ Live match data upserted successfully

In [24]:
## Incremental Updates

#  Fetch the DB snapshot

import pandas as pd

db_query = """
SELECT
    match_id,
    team1_runs,
    team1_wickets,
    team1_overs,
    team2_runs,
    team2_wickets,
    team2_overs,
    state,
    status
FROM live_matches;
"""

df_existing = pd.read_sql(db_query, conn)

C:\Users\Suba\AppData\Local\Temp\ipykernel_37568\2426229426.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_existing = pd.read_sql(db_query, conn)

In [25]:
# Prepare for comparison (very important)
# ❗ Rule: comparisons must be NULL-safe

df_existing = df_existing.where(pd.notnull(df_existing), None)
df_matches = df_matches.where(pd.notnull(df_matches), None)

import numpy as np

df_existing = df_existing.replace({np.nan: None})

In [26]:
# create a lookup dict from existing DB data for easy comparison

existing_lookup = (
    df_existing
    .set_index("match_id")
    .to_dict(orient="index")
)

In [27]:
existing_lookup[146950]

{'team1_runs': 91.0,
 'team1_wickets': 10.0,
 'team1_overs': 16.5,
 'team2_runs': 95.0,
 'team2_wickets': 6.0,
 'team2_overs': 17.4,
 'state': 'Complete',
 'status': 'Bahrain won by 4 wkts'}

In [28]:
# Define COMPARE_COLS first

COMPARE_COLS = [
    "team1_runs", "team1_wickets", "team1_overs",
    "team2_runs", "team2_wickets", "team2_overs",
    "state", "status"
]

In [29]:
# (Optional but PRO) Make comparison bulletproof
# If you want extra safety, update the comparison function:

import math

def values_equal(a, b):
    if a is None and b is None:
        return True
    return a == b

In [30]:
def has_match_changed(new_row, old_row):
    for col in COMPARE_COLS:
        if not values_equal(new_row[col], old_row[col]):
            return True
    return False

In [31]:
import numpy as np

df_matches = df_matches.replace({np.nan: None})

In [32]:
update_query = """
UPDATE live_matches
SET
    team1_runs = %(team1_runs)s,
    team1_wickets = %(team1_wickets)s,
    team1_overs = %(team1_overs)s,
    team2_runs = %(team2_runs)s,
    team2_wickets = %(team2_wickets)s,
    team2_overs = %(team2_overs)s,
    state = %(state)s,
    status = %(status)s,
    last_updated = CURRENT_TIMESTAMP
WHERE match_id = %(match_id)s;
"""

In [33]:
# INSERT vs UPDATE decision flow

inserts = 0
updates = 0
skips = 0

for _, row in df_matches.iterrows():
    match_id = row["match_id"]
    row_dict = row.to_dict()

    if match_id not in existing_lookup:
        # NEW MATCH → INSERT
        cursor.execute(insert_query, row_dict)
        inserts += 1

    else:
        # EXISTING MATCH → COMPARE
        old_data = existing_lookup[match_id]

        if has_match_changed(row_dict, old_data):
            cursor.execute(update_query, row_dict)
            updates += 1
        else:
            skips += 1

In [34]:
# Commit + logging

conn.commit()

print("Incremental update summary:")
print(f"Inserted: {inserts}")
print(f"Updated: {updates}")
print(f"Skipped : {skips}")

Incremental update summary:
Inserted: 0
Updated: 0
Skipped : 7

In [35]:
### 3. Analytics functions

import numpy as np

TOTAL_OVERS = {
    "T20": 20,
    "ODI": 50,
    "TEST": None
}

def compute_match_analytics(row):
    analytics = {}

    format_ = row["match_format"]
    total_overs = TOTAL_OVERS.get(format_)

    # ---------- CRR ----------
    if row["team2_runs"] is not None and row["team2_overs"] and row["team2_overs"] > 0:
        analytics["current_run_rate"] = round(row["team2_runs"] / row["team2_overs"], 2)
    else:
        analytics["current_run_rate"] = None

    # ---------- RRR ----------
    if (
        total_overs
        and row["team1_runs"] is not None
        and row["team2_runs"] is not None
        and row["team2_overs"] is not None
    ):
        runs_needed = row["team1_runs"] + 1 - row["team2_runs"]
        overs_remaining = total_overs - row["team2_overs"]

        if overs_remaining > 0:
            analytics["required_run_rate"] = round(runs_needed / overs_remaining, 2)
        else:
            analytics["required_run_rate"] = None
    else:
        analytics["required_run_rate"] = None

    # ---------- Match Phase ----------
    if row["team2_overs"] is not None:
        if row["team2_overs"] <= 6:
            analytics["match_phase"] = "Powerplay"
        elif row["team2_overs"] <= 15:
            analytics["match_phase"] = "Middle"
        else:
            analytics["match_phase"] = "Death"
    else:
        analytics["match_phase"] = None

    # ---------- Pressure ----------
    if analytics["current_run_rate"] and analytics["required_run_rate"]:
        analytics["pressure"] = round(
            analytics["required_run_rate"] - analytics["current_run_rate"], 2
        )
    else:
        analytics["pressure"] = None

    return analytics

In [36]:
# Apply to your DB dataframe

analytics_rows = []

for _, row in df_db.iterrows():
    metrics = compute_match_analytics(row)
    analytics_rows.append({
        "match_id": row["match_id"],
        **metrics
    })

df_analytics = pd.DataFrame(analytics_rows)

In [37]:
### 4. WIN PROBABILITY MODEL

import math
import numpy as np

def safe_div(n, d):
    if d is None or d == 0 or pd.isna(d):
        return None
    return n / d

In [38]:
# Match format context (par scores)
# Simple domain knowledge (VERY interview-friendly):

PAR_SCORES = {
    "T20": 160,
    "ODI": 280,
    "TEST": 350
}

MAX_OVERS = {
    "T20": 20,
    "ODI": 50
}

In [39]:
# Match phase detector

def get_match_phase(overs, match_format):
    if match_format not in MAX_OVERS or overs is None:
        return "UNKNOWN"
    
    max_overs = MAX_OVERS[match_format]

    if overs <= max_overs * 0.3:
        return "POWERPLAY"
    elif overs <= max_overs * 0.75:
        return "MIDDLE"
    else:
        return "DEATH"

In [40]:
# Core win probability logic (CHASE scenario)
# This is the heart of the model

def win_prob_chasing(row):
    runs_scored = row["team2_runs"]
    wickets_lost = row["team2_wickets"]
    overs_played = row["team2_overs"]
    target = row["team1_runs"] + 1
    match_format = row["match_format"]

    if any(pd.isna(x) for x in [runs_scored, wickets_lost, overs_played]):
        return None, None

    balls_remaining = (MAX_OVERS[match_format] * 6) - int(overs_played * 6)
    runs_required = target - runs_scored
    wickets_remaining = 10 - wickets_lost

    rrr = safe_div(runs_required * 6, balls_remaining)
    pressure = rrr * (1 + (10 - wickets_remaining) * 0.05)

    # heuristic score
    score = 100 - pressure * 10
    score = max(5, min(score, 95))

    return round(score, 2), round(100 - score, 2)

In [41]:
# First innings projection logic

def win_prob_first_innings(row):
    runs = row["team1_runs"]
    overs = row["team1_overs"]
    wickets = row["team1_wickets"]
    match_format = row["match_format"]

    if any(pd.isna(x) for x in [runs, overs, wickets]):
        return None, None

    crr = safe_div(runs, overs)
    projected = runs + crr * (MAX_OVERS.get(match_format, 20) - overs)

    par = PAR_SCORES.get(match_format, 160)

    diff = projected - par
    prob = 50 + diff * 0.2
    prob = max(30, min(prob, 70))

    return round(prob, 2), round(100 - prob, 2)

In [42]:
# Unified win probability engine

def calculate_win_probability(row):
    # second innings if team2 has started batting
    if not pd.isna(row["team2_runs"]):
        p1, p2 = win_prob_chasing(row)
    else:
        p1, p2 = win_prob_first_innings(row)

    return pd.Series({
        "win_prob_team1": p1,
        "win_prob_team2": p2,
        "match_phase": get_match_phase(
            row["team2_overs"] if not pd.isna(row["team2_overs"]) else row["team1_overs"],
            row["match_format"]
        )
    })

In [43]:
# Apply to your dataframe

win_prob_df = df_db.apply(calculate_win_probability, axis=1)
df_enriched = pd.concat([df_db, win_prob_df], axis=1)

In [44]:
# now inspect

df_enriched[[
    "match_id",
    "match_format",
    "state",
    "team1_runs",
    "team2_runs",
    "win_prob_team1",
    "win_prob_team2",
    "match_phase"
]]

,match_id,match_format,state,team1_runs,team2_runs,win_prob_team1,win_prob_team2,match_phase
0,146950,T20,Complete,91.0,95.0,95.0,5.0,DEATH
1,146939,T20,Complete,157.0,120.0,5.0,95.0,DEATH
2,147700,T20,Complete,182.0,186.0,95.0,5.0,DEATH
3,125085,TEST,Rain,527.0,None,30.0,70.0,UNKNOWN
4,147170,ODI,Toss,None,None,NaN,NaN,UNKNOWN
5,147159,ODI,Toss,None,None,NaN,NaN,UNKNOWN
6,122737,T20,Complete,202.0,110.0,5.0,95.0,DEATH

In [ ]:
# # PRODUCTION HARDENING (REAL-WORLD ENGINEERING)
# You already have:
# Live API ingestion ✅
# Normalized PostgreSQL table ✅
# Incremental updates ✅
# Win probability model ✅
# Now we make it robust, fast, and auditable

In [45]:
# Prepare dataframe for DB write

df_to_update = df_enriched[[
    "match_id",
    "win_prob_team1",
    "win_prob_team2",
    "match_phase"
]].copy()

df_to_update["model_version"] = MODEL_VERSION

In [46]:
# Update query (safe + idempotent)

update_model_query = """
UPDATE live_matches
SET
    win_prob_team1 = %(win_prob_team1)s,
    win_prob_team2 = %(win_prob_team2)s,
    match_phase = %(match_phase)s,
    model_version = %(model_version)s,
    last_calculated = CURRENT_TIMESTAMP
WHERE match_id = %(match_id)s
"""

In [48]:
# Execute updates (transaction-safe)

updates = 0

try:
    for _, row in df_to_update.iterrows():
        cursor.execute(update_model_query, row.to_dict())
        updates += 1

    conn.commit()
    print(f"✅ Win probabilities updated for {updates} matches")

except Exception as e:
    conn.rollback()
    raise e

✅ Win probabilities updated for 7 matches

In [1]:
# scrape players bat/bow style

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/2/players"

headers = {
	"x-rapidapi-key": "5e5dbe818cmsha460f5285388e99p1e0f41jsn0b032a980a81",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [2]:
data.keys()

dict_keys(['player'])

In [36]:
data["player"]

[{'name': 'BATSMEN', 'imageId': 174146},
 {'id': '11808',
  'name': 'Shubman Gill',
  'imageId': 616515,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '13940',
  'name': 'Yashasvi Jaiswal',
  'imageId': 591942,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '13866',
  'name': 'Sai Sudharsan',
  'imageId': 717782,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '576',
  'name': 'Rohit Sharma',
  'imageId': 616514,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '1413',
  'name': 'Virat Kohli',
  'imageId': 616517,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm medium'},
 {'id': '7915',
  'name': 'Suryakumar Yadav',
  'imageId': 846028,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '9428',
  'name': 'Shreyas Iyer',
  'imageId': 616518,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '10896',
  'name': 'Rinku Singh',
  'imageId': 846030,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '14504',
  'name': 'Tilak Varma',
  'imageId': 846029,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '11813',
  'name': 'Ruturaj Gaikwad',
  'imageId': 781069,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '10636',
  'name': 'Rajat Patidar',
  'imageId': 760758,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '9429',
  'name': 'Sarfaraz Khan',
  'imageId': 591955,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '9716',
  'name': 'Abhimanyu Easwaran',
  'imageId': 591956,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '8257',
  'name': 'Karun Nair',
  'imageId': 717781,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'name': 'ALL ROUNDER', 'imageId': 174146},
 {'id': '14701',
  'name': 'Nitish Kumar Reddy',
  'imageId': 591947,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '9647',
  'name': 'Hardik Pandya',
  'imageId': 846032,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '11195',
  'name': 'Shivam Dube',
  'imageId': 846034,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm medium'},
 {'id': '12086',
  'name': 'Abhishek Sharma',
  'imageId': 846031,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'id': '587',
  'name': 'Ravindra Jadeja',
  'imageId': 616520,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'id': '8683',
  'name': 'Shardul Thakur',
  'imageId': 352487,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '10945',
  'name': 'Washington Sundar',
  'imageId': 616522,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Right-arm offbreak'},
 {'id': '8808',
  'name': 'Axar Patel',
  'imageId': 846033,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm orthodox'},
 {'name': 'WICKET KEEPER', 'imageId': 174146},
 {'id': '10744',
  'name': 'Rishabh Pant',
  'imageId': 616524,
  'battingStyle': 'Left-hand bat'},
 {'id': '8733',
  'name': 'KL Rahul',
  'imageId': 616523,
  'battingStyle': 'Right-hand bat'},
 {'id': '14691',
  'name': 'Dhruv Jurel',
  'imageId': 591954,
  'battingStyle': 'Right-hand bat'},
 {'id': '8271',
  'name': 'Sanju Samson',
  'imageId': 846035,
  'battingStyle': 'Right-hand bat'},
 {'id': '10276',
  'name': 'Ishan Kishan',
  'imageId': 846036,
  'battingStyle': 'Left-hand bat'},
 {'name': 'BOWLER', 'imageId': 174146},
 {'id': '10808',
  'name': 'Mohammed Siraj',
  'imageId': 591952,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '9311',
  'name': 'Jasprit Bumrah',
  'imageId': 846037,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '10551',
  'name': 'Prasidh Krishna',
  'imageId': 591958,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast'},
 {'id': '14726',
  'name': 'Akash Deep',
  'imageId': 591951,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '8292',
  'name': 'Kuldeep Yadav',
  'imageId': 846039,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm wrist-spin'},
 {'id': '13217',
  'name': 'Arshdeep Singh',
  'imageId': 846038,
  'battingStyle': 'Left-hand bat',
  'bowlingStyle': 'Left-arm fast-medium'},
 {'id': '24729',
  'name': 'Harshit Rana',
  'imageId': 616529,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '14659',
  'name': 'Ravi Bishnoi',
  'imageId': 226280,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'},
 {'id': '10754',
  'name': 'Mukesh Kumar',
  'imageId': 333872,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm fast-medium'},
 {'id': '12926',
  'name': 'Varun Chakaravarthy',
  'imageId': 846040,
  'battingStyle': 'Right-hand bat',
  'bowlingStyle': 'Right-arm legbreak'}]

In [37]:
import pandas as pd
import numpy as np

players_list = []

# Loop through all values in the dict
for v in data.values():
    # v can be a list of dicts
    if isinstance(v, list):
        for p in v:
            if 'id' in p:  # only real players
                players_list.append({
                    'player_id': int(p['id']),
                    'full_name': p.get('name'),
                    'batting_style': p.get('battingStyle'),
                    'bowling_style': p.get('bowlingStyle'),
                    'image_id': p.get('imageId')
                })

df_players = pd.DataFrame(players_list)

# DB-friendly cleaning
df_db = df_players.replace({np.nan: None}).where(pd.notnull(df_players), None)

print(df_db.head())
print("Total players:", len(df_db))

   player_id         full_name   batting_style       bowling_style  image_id
0      11808      Shubman Gill  Right-hand bat  Right-arm offbreak    616515
1      13940  Yashasvi Jaiswal   Left-hand bat  Right-arm legbreak    591942
2      13866     Sai Sudharsan   Left-hand bat  Right-arm legbreak    717782
3        576      Rohit Sharma  Right-hand bat  Right-arm offbreak    616514
4       1413       Virat Kohli  Right-hand bat    Right-arm medium    616517
Total players: 37

In [38]:
import psycopg2
import pandas as pd
import numpy as np

# DB config
secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")


# Create table if not exists
cursor.execute("""
CREATE TABLE IF NOT EXISTS players (
    player_id INTEGER PRIMARY KEY,
    full_name TEXT,
    batting_style TEXT,
    bowling_style TEXT,
    image_id INTEGER
)
""")
conn.commit()

# Upsert each row
for _, row in df_db.iterrows():
    cursor.execute("""
    INSERT INTO players (player_id, full_name, batting_style, bowling_style, image_id)
    VALUES (%s, %s, %s, %s, %s)
    ON CONFLICT (player_id) DO UPDATE
    SET full_name = EXCLUDED.full_name,
        batting_style = EXCLUDED.batting_style,
        bowling_style = EXCLUDED.bowling_style,
        image_id = EXCLUDED.image_id
    """, (row['player_id'], row['full_name'], row['batting_style'], row['bowling_style'], row['image_id']))

conn.commit()
conn.close()
print("✅ Player data ETL completed successfully with psycopg2!")

Connected to DB
✅ Player data ETL completed successfully with psycopg2!

In [42]:
## fetching only the role from this api and integrating into the players table

player_ids = [
    576,587,1413,7915,8257,8271,8292,8683,8733,8808,
    9311,9428,9429,9647,9716,10276,10551,10636,10744,
    10754,10808,10896,10945,11195,11808,11813,12086,
    12926,13217,13866,13940,14504,14659,14691,14701,
    14726,24729
]

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{}"
headers = {
    "x-rapidapi-key": "e02a731416msha2f7089fb7e8170p1f773ejsne149d4f6ce02",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

In [46]:
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [47]:
for pid in player_ids:
    response = requests.get(url.format(pid), headers=headers)

    if response.status_code != 200:
        continue

    data = response.json()
    role = data.get("role")

    if role:
        cursor.execute("""
            UPDATE players
            SET playing_role = %s
            WHERE player_id = %s
        """, (role, pid))

conn.commit()
cursor.close()
conn.close()

In [9]:
## scrape recent matches data


from datetime import datetime

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"
headers = {
    "x-rapidapi-key": "3cdc535360mshc729ab2d422c376p16cacbjsnc90870850ea6",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)
data = response.json()

In [10]:
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [11]:
for type_match in data.get("typeMatches", []):
    match_type = type_match.get("matchType")

    for series_block in type_match.get("seriesMatches", []):
        wrapper = series_block.get("seriesAdWrapper")
        if not wrapper:
            continue

        series_name = wrapper.get("seriesName")

        for match in wrapper.get("matches", []):
            info = match.get("matchInfo", {})

            match_id = info.get("matchId")
            match_desc = info.get("matchDesc")
            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")
            status = info.get("status")
            venue = info.get("venueInfo", {}).get("ground")

            start_date = None
            if info.get("startDate"):
                start_date = datetime.fromtimestamp(
                    int(info["startDate"]) / 1000
                )

            if not match_id:
                continue

            cursor.execute("""
                INSERT INTO recent_matches (
                    match_id, match_type, series_name, match_desc,
                    team1, team2, venue, status, start_date
                )
                VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
                ON CONFLICT (match_id) DO UPDATE SET
                    status = EXCLUDED.status,
                    last_updated = CURRENT_TIMESTAMP
            """, (
                match_id, match_type, series_name, match_desc,
                team1, team2, venue, status, start_date
            ))

conn.commit()
cursor.close()
conn.close()

In [129]:
## Scrape odi batting stats

# -------------------- API CONFIG --------------------
URL = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"
HEADERS = {
    "x-rapidapi-key": "9f30a5ea42msh0005dbc02912d8bp14cb16jsnf4e0be024910",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

In [130]:
# scrape centuaries data

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

querystring = {"statsType":"mostHundreds","matchType":"2"}

headers = {
	"x-rapidapi-key": "9f30a5ea42msh0005dbc02912d8bp14cb16jsnf4e0be024910",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

print("Status Code:", response.status_code)
data = response.json()

print("HEADERS:")
print(json.dumps(data["headers"], indent=2))

print("\nSAMPLE VALUES:")
print(json.dumps(data["values"][:5], indent=2))

Status Code: 200
HEADERS:
[
  "Batter",
  "M",
  "I",
  "R",
  "100s"
]

SAMPLE VALUES:
[
  {
    "values": [
      "1413",
      "Virat Kohli",
      "311",
      "299",
      "14797",
      "54"
    ]
  },
  {
    "values": [
      "25",
      "Tendulkar",
      "463",
      "452",
      "18426",
      "49"
    ]
  },
  {
    "values": [
      "576",
      "Rohit Sharma",
      "282",
      "274",
      "11577",
      "33"
    ]
  },
  {
    "values": [
      "38",
      "R Ponting",
      "375",
      "365",
      "13704",
      "30"
    ]
  },
  {
    "values": [
      "102",
      "S Jayasuriya",
      "445",
      "433",
      "13430",
      "28"
    ]
  }
]

In [131]:
# 1️⃣ FETCH MOST RUNS (ODI)
# --------------------------------
runs_params = {"statsType": "mostRuns", "matchType": "2"}
runs_json = requests.get(URL, headers=HEADERS, params=runs_params).json()

runs_map = {}

# Skip junk rows
for row in runs_json["values"]:
    vals = row["values"]

    if not vals[0].isdigit():
        continue

    player_id = int(vals[0])
    player_name = vals[1]

    runs_map[player_id] = {
        "player_name": player_name,
        "matches": int(vals[2]),
        "innings": int(vals[3]),
        "runs": int(vals[4]),
        "batting_avg": float(vals[5])
    }

In [132]:
# 2️⃣ FETCH MOST HUNDREDS (ODI)
# --------------------------------
hundreds_params = {"statsType": "mostHundreds", "matchType": "2"}
hundreds_json = requests.get(URL, headers=HEADERS, params=hundreds_params).json()

hundreds_map = {}

for row in hundreds_json["values"]:
    vals = row["values"]

    if not vals[0].isdigit():
        continue

    player_id = int(vals[0])
    centuries = int(vals[5])  # ✅ CORRECT INDEX

    hundreds_map[player_id] = centuries

In [133]:
import psycopg2
import requests
from datetime import datetime

# 1️⃣ Open connection
secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)

# 2️⃣ Create cursor
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [134]:
for player_id, stats in runs_map.items():
    centuries = hundreds_map.get(player_id, 0)

    cursor.execute("""
        INSERT INTO odi_batting_stats (
            player_id,
            player_name,
            matches,
            innings,
            runs,
            batting_avg,
            centuries,
            last_updated
        )
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (player_id)
        DO UPDATE SET
            player_name = EXCLUDED.player_name,
            matches = EXCLUDED.matches,
            innings = EXCLUDED.innings,
            runs = EXCLUDED.runs,
            batting_avg = EXCLUDED.batting_avg,
            centuries = EXCLUDED.centuries,
            last_updated = EXCLUDED.last_updated
    """, (
        player_id,
        stats["player_name"],
        stats["matches"],
        stats["innings"],
        stats["runs"],
        stats["batting_avg"],
        centuries,
        datetime.now()
    ))

# 4️⃣ Commit
conn.commit()

print("✅ Data inserted successfully")

✅ Data inserted successfully

In [135]:
# build runs map

runs_map = {}

for row in runs_data:
    vals = row["values"]

    if not vals[0].isdigit():
        continue

    player_id = int(vals[0])

    runs_map[player_id] = {
        "player_name": vals[1],
        "matches": int(vals[2]),
        "innings": int(vals[3]),
        "runs": int(vals[4]),
        "batting_avg": float(vals[5])
    }

print(f"Runs map size: {len(runs_map)}")

Runs map size: 20

In [136]:
print(hundreds_data.keys())

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [137]:
# BUILD hundreds_map

hundreds_rows = hundreds_data["values"]

hundreds_map = {}

for row in hundreds_rows:
    vals = row.get("values", [])

    if len(vals) < 6:
        continue

    if not vals[0].isdigit():
        continue

    player_id = int(vals[0])
    centuries = int(vals[5])

    hundreds_map[player_id] = centuries

print("Hundreds map size:", len(hundreds_map))


# ---------------------------
# 4️⃣ LOAD INTO POSTGRES
# ---------------------------
insert_sql = """
INSERT INTO odi_batting_stats (
    player_id,
    player_name,
    matches,
    innings,
    runs,
    batting_avg,
    centuries,
    last_updated
)
VALUES (%s,%s,%s,%s,%s,%s,%s,NOW())
ON CONFLICT (player_id)
DO UPDATE SET
    player_name = EXCLUDED.player_name,
    matches = EXCLUDED.matches,
    innings = EXCLUDED.innings,
    runs = EXCLUDED.runs,
    batting_avg = EXCLUDED.batting_avg,
    centuries = EXCLUDED.centuries,
    last_updated = NOW();
"""

for pid, data in runs_map.items():
    cursor.execute(insert_sql, (
        pid,
        data["player_name"],
        data["matches"],
        data["innings"],
        data["runs"],
        data["batting_avg"],
        hundreds_map.get(pid, 0)   # ✅ safe join
    ))

conn.commit()
print("✅ ODI batting stats loaded successfully")

cursor.close()
conn.close()

Hundreds map size: 20
✅ ODI batting stats loaded successfully

In [140]:
# adding the remaining players odi 100s values

from datetime import datetime

# ---------------------------
# DB CONNECTION
# ---------------------------
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

# ---------------------------
# GET PLAYER IDS
# ---------------------------
cursor.execute("SELECT player_id FROM odi_batting_stats")
player_ids = [row[0] for row in cursor.fetchall()]

# ---------------------------
# API CONFIG
# ---------------------------
url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{}/batting"
headers = {
    "x-rapidapi-key": "9f30a5ea42msh0005dbc02912d8bp14cb16jsnf4e0be024910",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# ---------------------------
# EXTRACT + UPDATE ODI 100s
# ---------------------------
for pid in player_ids:
    response = requests.get(url.format(pid), headers=headers)

    if response.status_code != 200:
        print(f"❌ API failed for player {pid}")
        continue

    data = response.json()
    odi_centuries = 0

    for row in data.get("values", []):
        vals = row.get("values", [])

        # Look for the "100s" row
        if vals and vals[0] == "100s":
            odi_centuries = int(vals[2])  # ✅ ODI column
            break

    cursor.execute("""
        UPDATE odi_batting_stats
        SET centuries = %s,
            last_updated = %s
        WHERE player_id = %s
    """, (odi_centuries, datetime.now(), pid))

conn.commit()
cursor.close()
conn.close()

print("✅ ODI centuries populated correctly")

Connected to DB
✅ ODI centuries populated correctly

In [71]:
## cricket venues that have a seating capacity of more than 25,000 spectators

import requests
import re


venue_ids = [42, 36, 35, 46, 50, 55, 76, 80, 84, 87]

URL = "https://cricbuzz-cricket.p.rapidapi.com/venues/v1/{}"
HEADERS = {
    "x-rapidapi-key": "235eafff71msh04162be1af40ec0p1aef01jsnee3bf4d54dd6",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

In [72]:
# Capacity cleaning function

def clean_capacity(capacity):
    if not capacity:
        return None
    nums = re.findall(r"\d+", capacity)
    return int("".join(nums)) if nums else None

print("Venues with capacity > 25,000\n")

Venues with capacity > 25,000

In [73]:
for vid in venue_ids:
    response = requests.get(url.format(vid), headers=headers)
    data = response.json()

    capacity = clean_capacity(data.get("capacity"))

    if capacity and capacity > 25000:
        print(f"Venue Name : {data.get('ground')}")
        print(f"City       : {data.get('city')}")
        print(f"Country    : {data.get('country')}")
        print(f"Capacity   : {capacity}")
        print("-" * 50)

In [77]:
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [78]:
# ---------------- LOAD ----------------
for vid in venue_ids:
    response = requests.get(url.format(vid), headers=headers)
    data = response.json()

    capacity = clean_capacity(data.get("capacity"))

    cursor.execute("""
        INSERT INTO venue (venue_id, ground, city, country, capacity)
        VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT (venue_id) DO UPDATE
        SET
            ground = EXCLUDED.ground,
            city = EXCLUDED.city,
            country = EXCLUDED.country,
            capacity = EXCLUDED.capacity;
    """, (
        vid,
        data.get("ground"),
        data.get("city"),
        data.get("country"),
        capacity
    ))

conn.commit()
cursor.close()
conn.close()

print("✅ Venue data loaded into PostgreSQL")

✅ Venue data loaded into PostgreSQL

In [3]:
### scrape team wins data and build a leaderboard

# Question 5 Calculate how many matches each team has won. Show team name and total number of wins. Display teams with the most wins first.

import requests
from collections import defaultdict
import time

TEAM_IDS = [
    2, 96, 27, 3, 4, 5, 6, 9, 10, 11, 12, 13, 71, 72, 77,
    161, 185, 190, 287, 298, 300, 303, 304, 343, 527, 529,
    541, 44, 26, 7, 8, 14, 15, 23, 24, 25, 675
]

HEADERS = {
    "x-rapidapi-key":"e02a731416msha2f7089fb7e8170p1f773ejsne149d4f6ce02",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

BASE_URL = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/{}/results"


# Create a normalization rule

def normalize_team(team_name):
    if team_name.endswith(" A"):
        return team_name.replace(" A", "")
    return team_name

wins = defaultdict(int)

for team_id in TEAM_IDS:
    url = BASE_URL.format(team_id)

    try:
        response = requests.get(url, headers=HEADERS, timeout=10)
        response.raise_for_status()
        data = response.json()
    except Exception as e:
        print(f"Failed for teamId {team_id}: {e}")
        continue

    team_matches_data = data.get("teamMatchesData", [])

    for series in team_matches_data:
        match_map = series.get("matchDetailsMap")
        if not match_map:
            continue

        matches = match_map.get("match", [])
        for match in matches:
            match_info = match.get("matchInfo", {})
            status = match_info.get("status", "")

            # We only count completed matches with a clear winner
            if " won " not in status:
                continue

            winner = status.split(" won ")[0].strip()

            # Defensive check: ignore weird status strings
            if len(winner) > 40 or "Match" in winner:
                continue
            normalized_winner = normalize_team(winner)
            wins[normalized_winner] = wins.get(normalized_winner, 0) + 1

    # Be nice to the API (avoid rate limiting)
    time.sleep(0.3)

# Sort teams by wins (descending)
sorted_wins = sorted(wins.items(), key=lambda x: x[1], reverse=True)

print("\nTeam Wins Leaderboard\n" + "-" * 30)
for team, total_wins in sorted_wins:
    print(f"{team}: {total_wins}")

Team Wins Leaderboard
------------------------------
England: 21
India: 18
Pakistan: 17
South Africa: 15
West Indies: 13
New Zealand: 12
Afghanistan: 12
Zimbabwe: 12
Ireland: 11
Jersey: 11
Uganda: 11
Malaysia: 10
Sri Lanka: 9
Bangladesh: 9
United States of America: 9
Italy: 8
Oman: 8
Nepal: 8
Namibia: 8
Kuwait: 8
Denmark: 7
Australia: 6
Hong Kong: 6
Fiji: 6
Bermuda: 6
United Arab Emirates: 5
Netherlands: 5
Samoa: 5
Scotland: 5
Austria: 5
Germany: 4
Singapore: 4
Hong Kong, China: 4
Belgium: 4
Qatar: 3
Tanzania: 3
Malawi: 3
Papua New Guinea: 3
Cook Islands: 3
Vanuatu: 3
Bahrain: 2
Norway: 2
Nigeria: 2
Kenya: 2
Canada: 2
Philippines: 1
Japan: 1
Rwanda: 1
Botswana: 1
Portugal: 1
Cayman Islands: 1
Saudi Arabia: 1

In [16]:
# Convert to DataFrame

df_team_wins = pd.DataFrame(
    wins.items(),
    columns=["team_name", "total_wins"]
)

df_team_wins = df_team_wins.sort_values(
    by="total_wins",
    ascending=False
).reset_index(drop=True)

df_team_wins

                   team_name  total_wins
0                    England          21
1                      India          18
2                   Pakistan          17
3               South Africa          15
4                West Indies          13
5                New Zealand          12
6                Afghanistan          12
7                   Zimbabwe          12
8                    Ireland          11
9                     Jersey          11
10                    Uganda          11
11                  Malaysia          10
12                Bangladesh           9
13  United States of America           9
14                 Sri Lanka           9
15                      Oman           8
16                    Kuwait           8
17                     Italy           8
18                     Nepal           8
19                   Namibia           8
20                   Denmark           7
21                 Australia           6
22                      Fiji           6
23                 Hong Kong           6
24                   Bermuda           6
25                  Scotland           5
26      United Arab Emirates           5
27                     Samoa           5
28               Netherlands           5
29                   Austria           5
30          Hong Kong, China           4
31                   Germany           4
32                   Belgium           4
33                 Singapore           4
34                     Qatar           3
35          Papua New Guinea           3
36                    Malawi           3
37                  Tanzania           3
38                   Vanuatu           3
39              Cook Islands           3
40                    Canada           2
41                     Kenya           2
42                    Norway           2
43                   Bahrain           2
44                   Nigeria           2
45               Philippines           1
46                     Japan           1
47                    Rwanda           1
48                  Botswana           1
49                  Portugal           1
50            Cayman Islands           1
51              Saudi Arabia           1

In [20]:
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [21]:
for _, row in df_team_wins.iterrows():
    cursor.execute("""
        INSERT INTO team_wins (team_name, total_wins)
        VALUES (%s, %s)
        ON CONFLICT (team_name)
        DO UPDATE SET
            total_wins = EXCLUDED.total_wins,
            updated_at = CURRENT_TIMESTAMP;
    """, (row["team_name"], row["total_wins"]))

conn.commit()
cursor.close()
conn.close()

In [ ]:
# streamlit dashboard for team wins

# import streamlit as st
# import pandas as pd
# import psycopg2

# conn = psycopg2.connect(
#     host="localhost",
#     database="cricket_db",
#     user="postgres",
#     password="password"
# )

# df = pd.read_sql("""
#     SELECT team_name, total_wins
#     FROM team_wins
#     ORDER BY total_wins DESC
# """, conn)

# st.title("🏆 Team Wins Leaderboard")
# st.dataframe(df)

In [ ]:
# ### Question 7 Find the highest individual batting score achieved in each cricket format
# #  (Test, ODI, T20I). Display the format and the highest score for that format.

# # To check the keys

# import requests

# url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/1413/batting"

# headers = {
# 	"x-rapidapi-key": "e02a731416msha2f7089fb7e8170p1f773ejsne149d4f6ce02",
# 	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
# }

# response = requests.get(url, headers=headers)

# data = (response.json())

In [67]:
data.keys()

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [68]:
data['values']

[{'values': ['Matches', '10', '4', '4', '28']},
 {'values': ['Innings', '16', '4', '3', '22']},
 {'values': ['Runs', '396', '100', '90', '485']},
 {'values': ['Balls', '691', '99', '50', '365']},
 {'values': ['Highest', '114', '53', '74', '76']},
 {'values': ['Average', '26.4', '33.33', '45', '28.53']},
 {'values': ['SR', '57.31', '101.02', '180.00', '132.88']},
 {'values': ['Not Out', '1', '1', '1', '5']},
 {'values': ['Fours', '40', '3', '4', '31']},
 {'values': ['Sixes', '10', '5', '8', '25']},
 {'values': ['Ducks', '2', '0', '1', '1']},
 {'values': ['50s', '0', '1', '1', '2']},
 {'values': ['100s', '1', '0', '0', '0']},
 {'values': ['200s', '0', '0', '0', '0']},
 {'values': ['300s', '0', '0', '0', '0']},
 {'values': ['400s', '0', '0', '0', '0']}]

In [69]:
import pprint
pprint.pprint(response.json())

{'message': 'You have exceeded the MONTHLY quota for Requests on your current '
            'plan, BASIC. Upgrade your plan at '
            'https://rapidapi.com/cricketapilive/api/cricbuzz-cricket'}

In [57]:
# Create DataFrame
df = pd.DataFrame(data)

# Final answer: highest score per format
result_df = (
    df.groupby("format", as_index=False)
      .agg({"highest_score": "max"})
)

print(result_df)

  format  highest_score
0    ODI             52
1   T20I             35
2   Test              7

In [93]:
import requests

player_ids = [
    576,587,1413,7915,8257,8271,8292,8683,8733,8808,
    9311,9428,9429,9647,9716,10276,10551,10636,10744,
    10754,10808,10896,10945,11195,11808,11813,12086,
    12926,13217,13866,13940,14504,14659,14691,14701,
    14726,24729
]

headers = {
    "x-rapidapi-key": "772ba3c76amsh6317fe16e284c56p10ef17jsn66090597cc3b",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# Track highest scores
highest_scores = {
    "Test": 0,
    "ODI": 0,
    "T20I": 0
}

for pid in player_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{pid}/batting"
    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        continue

    data = response.json()

    for row in data.get("values", []):
        if row["values"][0] == "Highest":
            test = int(row["values"][1].replace("*", ""))
            odi  = int(row["values"][2].replace("*", ""))
            t20  = int(row["values"][3].replace("*", ""))

            highest_scores["Test"] = max(highest_scores["Test"], test)
            highest_scores["ODI"]  = max(highest_scores["ODI"], odi)
            highest_scores["T20I"] = max(highest_scores["T20I"], t20)

            break

print("Highest scores among given players:")
for fmt, score in highest_scores.items():
    print(f"{fmt}: {score}")

Highest scores among given players:
Test: 303
ODI: 264
T20I: 135

In [18]:
import requests
import pandas as pd
from sqlalchemy import create_engine

PLAYER_IDS = [
    576,587,1413,7915,8257,8271,8292,8683,8733,8808,
    9311,9428,9429,9647,9716,10276,10551,10636,10744,
    10754,10808,10896,10945,11195,11808,11813,12086,
    12926,13217,13866,13940,14504,14659,14691,14701,
    14726,24729
]

HEADERS = {
    "x-rapidapi-key": "2515604773mshdfea0aa3ffcae60p1db10djsn22720922fae5",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

def fetch_player_batting(player_id):
    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"
    response = requests.get(url, headers=HEADERS)

    if response.status_code == 200:
        return response.json()
    return None

In [19]:
rows = []

for pid in PLAYER_IDS:
    data = fetch_player_batting(pid)
    if not data:
        continue

    for row in data.get("values", []):
        if row["values"][0] == "Highest":

            test = int(row["values"][1].replace("*", ""))
            odi  = int(row["values"][2].replace("*", ""))
            t20  = int(row["values"][3].replace("*", ""))

            rows.append({"player_id": pid, "format": "Test", "highest_score": test})
            rows.append({"player_id": pid, "format": "ODI",  "highest_score": odi})
            rows.append({"player_id": pid, "format": "T20I", "highest_score": t20})

            break

In [20]:
df = pd.DataFrame(rows)
print(df.head())

   player_id format  highest_score
0        576   Test            212
1        576    ODI            264
2        576   T20I            121
3        587   Test            175
4        587    ODI             87

In [21]:
final_df = (
    df.groupby("format", as_index=False)
      .agg(highest_score=("highest_score", "max"))
)

print(final_df)

  format  highest_score
0    ODI            264
1   T20I            135
2   Test            303

In [22]:
final_df.to_sql(
    "format_wise_highest_scores",
    engine,
    if_exists="replace",
    index=False
)

3

In [ ]:
# streamlit format_wise_highest_scores table

# import streamlit as st
# import pandas as pd
# from sqlalchemy import create_engine

# engine = create_engine(
#     "postgresql+psycopg2://postgres:monineha@localhost:5432/cricbuzz"
# )

# df = pd.read_sql("format_wise_highest_scores", engine)
# st.title("Highest Batting Scores by Format")
# st.dataframe(df)

In [ ]:
### Question 8 Show all cricket series that started in the year 2024. 
# Include series name, host country, match type, start date, and total number of matches planned.


import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"

querystring = {"year":"2024"}

headers = {
	"x-rapidapi-key": "2515604773mshdfea0aa3ffcae60p1db10djsn22720922fae5",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

archives_data = response.json()

In [67]:
archives_data.keys()

dict_keys(['message'])

In [34]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/8553"

headers = {
	"x-rapidapi-key": "2515604773mshdfea0aa3ffcae60p1db10djsn22720922fae5",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

match_data = response.json()

In [35]:
match_data.keys()

dict_keys(['matchDetails', 'appIndex'])

In [36]:
match_data['matchDetails']

[{'matchDetailsMap': {'key': 'Mon, 23 Dec 2024',
   'match': [{'matchInfo': {'matchId': 112385,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': 'Practice Match 1',
      'matchFormat': 'T20',
      'startDate': '1734904800000',
      'endDate': '1734904800000',
      'state': 'complete',
      'status': 'Sri Lanka won by 7 wkts',
      'team1': {'teamId': 286,
       'teamName': 'NEW ZEALAND XI',
       'teamSName': 'NZXI',
       'imageId': 776339},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Bert Sutcliffe Oval',
       'city': 'Lincoln',
       'timezone': '+13:00'},
      'currBatTeamId': 5,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 94,
        'wickets': 10,
        'overs': 13.4}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 97,
        'wickets': 3,
        'overs': 10.5}}}},
    {'matchInfo': {'matchId': 112389,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': 'Practice Match 2',
      'matchFormat': 'T20',
      'startDate': '1734915600000',
      'endDate': '1734915600000',
      'state': 'complete',
      'status': 'Sri Lanka won by 32 runs',
      'team1': {'teamId': 286,
       'teamName': 'NEW ZEALAND XI',
       'teamSName': 'NZXI',
       'imageId': 776339},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Bert Sutcliffe Oval',
       'city': 'Lincoln',
       'timezone': '+13:00'},
      'currBatTeamId': 5,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 96,
        'wickets': 2,
        'overs': 10.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 128,
        'wickets': 2,
        'overs': 10.0}}}}],
   'seriesId': 8553}},
 {'adDetail': {'name': 'native_news_index_random_1',
   'layout': 'native_large',
   'position': 1}},
 {'matchDetailsMap': {'key': 'Sat, 28 Dec 2024',
   'match': [{'matchInfo': {'matchId': 102036,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': '1st T20I',
      'matchFormat': 'T20',
      'startDate': '1735366500000',
      'endDate': '1735366500000',
      'state': 'complete',
      'status': 'New Zealand won by 8 runs',
      'team1': {'teamId': 13,
       'teamName': 'NEW ZEALAND',
       'teamSName': 'NZ',
       'imageId': 776333},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Bay Oval',
       'city': 'Mount Maunganui',
       'timezone': '+13:00'},
      'currBatTeamId': 13,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 172,
        'wickets': 8,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 164,
        'wickets': 8,
        'overs': 20.0}}}}],
   'seriesId': 8553}},
 {'matchDetailsMap': {'key': 'Mon, 30 Dec 2024',
   'match': [{'matchInfo': {'matchId': 102040,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': '2nd T20I',
      'matchFormat': 'T20',
      'startDate': '1735539300000',
      'endDate': '1735539300000',
      'state': 'complete',
      'status': 'New Zealand won by 45 runs',
      'team1': {'teamId': 13,
       'teamName': 'NEW ZEALAND',
       'teamSName': 'NZ',
       'imageId': 776333},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Bay Oval',
       'city': 'Mount Maunganui',
       'timezone': '+13:00'},
      'currBatTeamId': 13,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 186,
        'wickets': 5,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 141,
        'wickets': 10,
        'overs': 19.1}}}}],
   'seriesId': 8553}},
 {'matchDetailsMap': {'key': 'Thu, 02 Jan 2025',
   'match': [{'matchInfo': {'matchId': 102045,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': '3rd T20I',
      'matchFormat': 'T20',
      'startDate': '1735776900000',
      'endDate': '1735776900000',
      'state': 'complete',
      'status': 'Sri Lanka won by 7 runs',
      'team1': {'teamId': 13,
       'teamName': 'NEW ZEALAND',
       'teamSName': 'NZ',
       'imageId': 776333},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Saxton Oval',
       'city': 'Nelson',
       'timezone': '+13:00'},
      'currBatTeamId': 5,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 211,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 218,
        'wickets': 5,
        'overs': 20.0}}}}],
   'seriesId': 8553}},
 {'matchDetailsMap': {'key': 'Sun, 05 Jan 2025',
   'match': [{'matchInfo': {'matchId': 102049,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': '1st ODI',
      'matchFormat': 'ODI',
      'startDate': '1736028000000',
      'endDate': '1736028000000',
      'state': 'complete',
      'status': 'New Zealand won by 9 wkts',
      'team1': {'teamId': 13,
       'teamName': 'NEW ZEALAND',
       'teamSName': 'NZ',
       'imageId': 776333},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Basin Reserve',
       'city': 'Wellington',
       'timezone': '+13:00'},
      'currBatTeamId': 13,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 180,
        'wickets': 1,
        'overs': 26.2}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 178,
        'wickets': 10,
        'overs': 43.4}}}}],
   'seriesId': 8553}},
 {'matchDetailsMap': {'key': 'Wed, 08 Jan 2025',
   'match': [{'matchInfo': {'matchId': 102058,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': '2nd ODI',
      'matchFormat': 'ODI',
      'startDate': '1736298000000',
      'endDate': '1736298000000',
      'state': 'complete',
      'status': 'New Zealand won by 113 runs (Match reduced to 37 ovs due to rain)',
      'team1': {'teamId': 13,
       'teamName': 'NEW ZEALAND',
       'teamSName': 'NZ',
       'imageId': 776333},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Seddon Park',
       'city': 'Hamilton',
       'timezone': '+13:00'},
      'currBatTeamId': 13,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 255,
        'wickets': 9,
        'overs': 37.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 142,
        'wickets': 10,
        'overs': 30.2}}}}],
   'seriesId': 8553}},
 {'matchDetailsMap': {'key': 'Sat, 11 Jan 2025',
   'match': [{'matchInfo': {'matchId': 102067,
      'seriesId': 8553,
      'seriesName': 'Sri Lanka tour of New Zealand, 2024-25',
      'matchDesc': '3rd ODI',
      'matchFormat': 'ODI',
      'startDate': '1736557200000',
      'endDate': '1736557200000',
      'state': 'complete',
      'status': 'Sri Lanka won by 140 runs',
      'team1': {'teamId': 13,
       'teamName': 'NEW ZEALAND',
       'teamSName': 'NZ',
       'imageId': 776333},
      'team2': {'teamId': 5,
       'teamName': 'SRI LANKA',
       'teamSName': 'SL',
       'imageId': 776254},
      'venueInfo': {'ground': 'Eden Park',
       'city': 'Auckland',
       'timezone': '+13:00'},
      'currBatTeamId': 5,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 150,
        'wickets': 10,
        'overs': 29.4}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 290,
        'wickets': 8,
        'overs': 50.0}}}}],
   'seriesId': 8553}}]

In [39]:
series_ids = []

for year_block in archives_data["seriesMapProto"]:
    for s in year_block["series"]:
        series_ids.append(s["id"])

print(f"Total series found: {len(series_ids)}")

Total series found: 109

In [38]:
print(type(archives_data))

<class 'dict'>

In [ ]:
# actual coding starts from here for this qn

import json
import requests

SERIES_ID = 8553  # any one series id
url = f"https://cricbuzz-cricket.p.rapidapi.com/series/v1/{SERIES_ID}"

headers = {
    "x-rapidapi-key": "2515604773mshdfea0aa3ffcae60p1db10djsn22720922fae5",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

resp = requests.get(url, headers=headers)

print("Status code:", resp.status_code)

data = resp.json()

# pretty print first level
print(json.dumps(data, indent=2)[:3000])

Status code: 200
{
  "matchDetails": [
    {
      "matchDetailsMap": {
        "key": "Mon, 23 Dec 2024",
        "match": [
          {
            "matchInfo": {
              "matchId": 112385,
              "seriesId": 8553,
              "seriesName": "Sri Lanka tour of New Zealand, 2024-25",
              "matchDesc": "Practice Match 1",
              "matchFormat": "T20",
              "startDate": "1734904800000",
              "endDate": "1734904800000",
              "state": "complete",
              "status": "Sri Lanka won by 7 wkts",
              "team1": {
                "teamId": 286,
                "teamName": "NEW ZEALAND XI",
                "teamSName": "NZXI",
                "imageId": 776339
              },
              "team2": {
                "teamId": 5,
                "teamName": "SRI LANKA",
                "teamSName": "SL",
                "imageId": 776254
              },
              "venueInfo": {
                "ground": "Bert Sutcliffe Oval",
                "city": "Lincoln",
                "timezone": "+13:00"
              },
              "currBatTeamId": 5,
              "isTimeAnnounced": true
            },
            "matchScore": {
              "team1Score": {
                "inngs1": {
                  "inningsId": 1,
                  "runs": 94,
                  "wickets": 10,
                  "overs": 13.4
                }
              },
              "team2Score": {
                "inngs1": {
                  "inningsId": 2,
                  "runs": 97,
                  "wickets": 3,
                  "overs": 10.5
                }
              }
            }
          },
          {
            "matchInfo": {
              "matchId": 112389,
              "seriesId": 8553,
              "seriesName": "Sri Lanka tour of New Zealand, 2024-25",
              "matchDesc": "Practice Match 2",
              "matchFormat": "T20",
              "startDate": "1734915600000",
              "endDate": "1734915600000",
              "state": "complete",
              "status": "Sri Lanka won by 32 runs",
              "team1": {
                "teamId": 286,
                "teamName": "NEW ZEALAND XI",
                "teamSName": "NZXI",
                "imageId": 776339
              },
              "team2": {
                "teamId": 5,
                "teamName": "SRI LANKA",
                "teamSName": "SL",
                "imageId": 776254
              },
              "venueInfo": {
                "ground": "Bert Sutcliffe Oval",
                "city": "Lincoln",
                "timezone": "+13:00"
              },
              "currBatTeamId": 5,
              "isTimeAnnounced": true
            },
            "matchScore": {
              "team1Score": {
                "inngs1": {
                  "inningsId": 2,
                  "runs": 96,
                  "wickets": 2,
                  "overs": 10.0
                }
              },
              "team2Score": {

In [1]:
import requests
import pandas as pd
import time

HEADERS = {
    "x-rapidapi-key": "5e5dbe818cmsha460f5285388e99p1e0f41jsn0b032a980a81",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

ARCHIVE_URL = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"
SERIES_URL = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/{}"

resp = requests.get(ARCHIVE_URL, headers=HEADERS, params={"year": "2024"})
archives_data = resp.json()

In [3]:
series_rows = []

for year_block in archives_data["seriesMapProto"]:
    for s in year_block["series"]:

        series_id = s["id"]
        series_name = s["name"]
        start_date = pd.to_datetime(
            int(s["startDt"]) // 1000,
            unit="s",
            errors="coerce"
    )

        # --- call series API only once per series ---
        resp = requests.get(SERIES_URL.format(series_id), headers=HEADERS)
        data = resp.json()

        match_count = 0
        formats = set()

        for block in data.get("matchDetails", []):
            mdm = block.get("matchDetailsMap")
            if not mdm:
                continue

            for match in mdm.get("match", []):
                match_count += 1
                fmt = match.get("matchInfo", {}).get("matchFormat")
                if fmt:
                    formats.add(fmt)

        series_rows.append({
            "series_id": series_id,
            "series_name": series_name,
            "host_country": series_name.split(" tour of ")[-1].split(",")[0],
            "match_types": ", ".join(sorted(formats)),
            "start_date": start_date,
            "total_matches": match_count
        })

        time.sleep(0.3)

In [5]:
df_series_2024 = pd.DataFrame(series_rows)
print(df_series_2024.shape)
df_series_2024.head()

(109, 6)

,series_id,series_name,host_country,match_types,start_date,total_matches
0,8553,"Sri Lanka tour of New Zealand, 2024-25",New Zealand,"ODI, T20",2024-12-23,8
1,9297,"Gulf Cricket T20I Championship, 2024",Gulf Cricket T20I Championship,T20,2024-12-13,16
2,8044,"Pakistan tour of South Africa, 2024 -25",South Africa,"ODI, T20, TEST",2024-12-10,8
3,9171,"Afghanistan tour of Zimbabwe, 2024-25",Zimbabwe,"ODI, T20, TEST",2024-12-09,8
4,9265,ICC Mens T20 World Cup Americas Sub Regional Q...,ICC Mens T20 World Cup Americas Sub Regional Q...,T20,2024-12-06,36

In [6]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:monineha@localhost:5432/cricbuzz"
)

df_series_2024.to_sql(
    "matches_2024",
    engine,
    if_exists="replace",   # use "append" later
    index=False
)

109

In [ ]:
# # Streamlit Dashboard
# import streamlit as st
# import pandas as pd

# df = pd.read_sql(
#     "SELECT * FROM matches_2024 ORDER BY start_date",
#     engine
# )

# st.title("Cricket Series Started in 2024")
# st.dataframe(df)

In [ ]:
### Question 9 Find all-rounder players who have scored more than 1000 runs 
# AND taken more than 50 wickets in their career. Display player name, total runs, total wickets, and the cricket format.

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/587/bowling"

headers = {
	"x-rapidapi-key": "5e5dbe818cmsha460f5285388e99p1e0f41jsn0b032a980a81",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

all_rounder_stats = response.json()

In [23]:
all_rounder_stats.keys()

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [33]:
all_rounder_stats["headers"]

['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL']

In [24]:
all_rounder_stats['values']

[{'values': ['Matches', '89', '210', '74', '254']},
 {'values': ['Innings', '167', '202', '71', '225']},
 {'values': ['Balls', '20241', '10404', '1356', '4056']},
 {'values': ['Runs', '8741', '8478', '1612', '5188']},
 {'values': ['Maidens', '770', '59', '4', '2']},
 {'values': ['Wickets', '348', '232', '54', '170']},
 {'values': ['Avg', '25.12', '36.54', '29.85', '30.52']},
 {'values': ['Eco', '2.59', '4.89', '7.13', '7.67']},
 {'values': ['SR', '58.16', '44.84', '25.11', '23.86']},
 {'values': ['BBI', '7/42', '5/33', '3/15', '5/16']},
 {'values': ['BBM', '10/110', '5/33', '3/15', '5/16']},
 {'values': ['4w', '17', '7', '0', '3']},
 {'values': ['5w', '15', '2', '0', '1']},
 {'values': ['10w', '3', '0', '0', '0']}]

In [38]:
import requests
import pandas as pd
import time

API_KEY = "5e5dbe818cmsha460f5285388e99p1e0f41jsn0b032a980a81"

HEADERS = {
    "x-rapidapi-key": API_KEY,
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

BASE_URL = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{}/bowling"

In [39]:
###
# Find out all-rounder players id

import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

cursor.execute("""
    SELECT player_id, player_name
    FROM players
    WHERE playing_role ILIKE '%allrounder%'
""")


all_rounders = cursor.fetchall()

Connected to DB

In [ ]:
# Transform – SCALE IT FOR ALL PLAYERS

all_records = []

for player_id, player_name in all_rounders:

    url = BASE_URL.format(player_id)
    resp = requests.get(url, headers=HEADERS)

    if resp.status_code != 200:
        continue

    data = resp.json()

    headers = data.get("headers", [])
    values = data.get("values", [])

    if not headers or not values:
        continue

    formats = headers[1:]  # remove ROWHEADER

    try:
        runs_row = next(r for r in values if r["values"][0] == "Runs")
        wickets_row = next(r for r in values if r["values"][0] == "Wickets")
    except StopIteration:
        continue

    runs_vals = runs_row["values"][1:]
    wickets_vals = wickets_row["values"][1:]

    for fmt, runs, wickets in zip(formats, runs_vals, wickets_vals):
        all_records.append({
            "player_id": player_id,
            "player_name": player_name,
            "cricket_format": fmt,
            "total_runs": int(runs),
            "total_wickets": int(wickets)
        })

    time.sleep(0.3)  # API safety

In [41]:
df_all_rounders = pd.DataFrame(all_records)
df_all_rounders

    player_id         player_name cricket_format  total_runs  total_wickets
0         587     Ravindra Jadeja           Test        8741            348
1         587     Ravindra Jadeja            ODI        8478            232
2         587     Ravindra Jadeja            T20        1612             54
3         587     Ravindra Jadeja            IPL        5188            170
4        8683      Shardul Thakur           Test        1024             33
5        8683      Shardul Thakur            ODI        2014             65
6        8683      Shardul Thakur            T20         772             33
7        8683      Shardul Thakur            IPL        3244            107
8        8808          Axar Patel           Test        1121             57
9        8808          Axar Patel            ODI        2461             75
10       8808          Axar Patel            T20        2016             93
11       8808          Axar Patel            IPL        4046            128
12       9647       Hardik Pandya           Test         528             17
13       9647       Hardik Pandya            ODI        3231             91
14       9647       Hardik Pandya            T20        3019            111
15       9647       Hardik Pandya            IPL        2492             78
16      10945   Washington Sundar           Test        1187             36
17      10945   Washington Sundar            ODI         837             29
18      10945   Washington Sundar            T20        1214             51
19      10945   Washington Sundar            IPL        1436             39
20      11195         Shivam Dube           Test           0              0
21      11195         Shivam Dube            ODI         106              1
22      11195         Shivam Dube            T20         832             31
23      11195         Shivam Dube            IPL         213              5
24      12086     Abhishek Sharma           Test           0              0
25      12086     Abhishek Sharma            ODI           0              0
26      12086     Abhishek Sharma            T20         234              6
27      12086     Abhishek Sharma            IPL         501             11
28      14701  Nitish Kumar Reddy           Test         366              8
29      14701  Nitish Kumar Reddy            ODI         106              0
30      14701  Nitish Kumar Reddy            T20          71              3
31      14701  Nitish Kumar Reddy            IPL         254              5

In [ ]:
# Insert from Python (UPSERT)

insert_sql = """
INSERT INTO all_rounder_stats
(player_id, cricket_format, total_runs, total_wickets)
VALUES (%s, %s, %s, %s)
ON CONFLICT (player_id, cricket_format)
DO UPDATE SET
    total_runs = EXCLUDED.total_runs,
    total_wickets = EXCLUDED.total_wickets;
"""

for _, row in df_all_rounders.iterrows():
    cursor.execute(
        insert_sql,
        (
            row["player_id"],
            row["cricket_format"],
            row["total_runs"],
            row["total_wickets"]
        )
    )

conn.commit()
print("All-rounder stats loaded")

All-rounder stats loaded

In [ ]:
# # streamlit 

# import streamlit as st
# import psycopg2
# import pandas as pd

# # -----------------------------
# # Page config
# # -----------------------------
# st.set_page_config(page_title="All-Rounder Analytics", layout="wide")
# st.title("🏏 All-Rounder Performance Dashboard")

# # -----------------------------
# # DB Connection
# # -----------------------------
# DB_CONFIG = {
#     "dbname": "cricbuzz",
#     "user": "postgres",
#     "password": "monineha",
#     "host": "localhost",
#     "port": 5432
# }

# conn = psycopg2.connect(**DB_CONFIG)

# # -----------------------------
# # Question 9 Query
# # -----------------------------
# query = """
# SELECT
#     p.player_name,
#     a.cricket_format,
#     a.total_runs,
#     a.total_wickets
# FROM all_rounder_stats a
# JOIN players p
#   ON p.player_id = a.player_id
# WHERE a.total_runs > 1000
#   AND a.total_wickets > 50
# ORDER BY p.player_name, a.cricket_format;
# """

# df = pd.read_sql(query, conn)

# # -----------------------------
# # Filters
# # -----------------------------
# st.sidebar.header("Filters")

# format_filter = st.sidebar.multiselect(
#     "Select Cricket Format",
#     options=df["cricket_format"].unique(),
#     default=df["cricket_format"].unique()
# )

# player_filter = st.sidebar.multiselect(
#     "Select Player",
#     options=df["player_name"].unique(),
#     default=df["player_name"].unique()
# )

# filtered_df = df[
#     (df["cricket_format"].isin(format_filter)) &
#     (df["player_name"].isin(player_filter))
# ]

# # -----------------------------
# # Display Table
# # -----------------------------
# st.subheader("All-Rounders (Runs > 1000 & Wickets > 50)")
# st.dataframe(filtered_df, use_container_width=True)

# # -----------------------------
# # Summary Metrics
# # -----------------------------
# st.subheader("Summary")

# col1, col2 = st.columns(2)

# col1.metric("Total Players", filtered_df["player_name"].nunique())
# col2.metric("Total Records", len(filtered_df))

In [ ]:
## Question 11 Compare each player's performance across different cricket formats. 
# For players who have played at least 2 different formats, 
# show their total runs in Test cricket, ODI cricket, and T20I cricket, along with their overall batting average across all formats.

import requests
import psycopg2

PLAYER_IDS = [
    576,587,1413,7915,8257,8271,8292,8683,8733,8808,
    9311,9428,9429,9647,9716,10276,10551,10636,10744,
    10754,10808,10896,10945,11195,11808,11813,12086,
    12926,13217,13866,13940,14504,14659,14691,14701,
    14726,24729
]

# 🔹 API headers
HEADERS = {
    "x-rapidapi-key": "ca8831ebb4mshc6fa8ff575d89aap1db4a1jsnc3cc6c6f77a4",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

FORMATS = ["Test", "ODI", "T20I", "IPL"]

for player_id in PLAYER_IDS:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"
    response = requests.get(url, headers=HEADERS)

    if response.status_code != 200:
        print(f"Failed for player {player_id}")
        continue

    data = response.json()

In [18]:
import psycopg2
import requests
import pandas as pd

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

Connected to DB

In [19]:
rows_for_df = []

# ---------------------------
# ETL LOOP
# ---------------------------
for player_id in PLAYER_IDS:

    # --- get player name ---
    player_url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}"
    player_resp = requests.get(player_url, headers=HEADERS).json()
    player_name = player_resp.get("name", "Unknown")

    # --- get batting stats ---
    stats_url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"
    stats_resp = requests.get(stats_url, headers=HEADERS).json()

    rows = stats_resp.get("values", [])

    runs_row = next(r for r in rows if r["values"][0] == "Runs")
    avg_row  = next(r for r in rows if r["values"][0] == "Average")

    for i, fmt in enumerate(FORMATS, start=1):
        runs = int(runs_row["values"][i])
        avg  = float(avg_row["values"][i])

        # ---- INSERT / UPSERT ----
        cursor.execute("""
            INSERT INTO player_batting_stats
                (player_id, player_name, format, runs, batting_average)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (player_id, format)
            DO UPDATE SET
                player_name = EXCLUDED.player_name,
                runs = EXCLUDED.runs,
                batting_average = EXCLUDED.batting_average;
        """, (player_id, player_name, fmt, runs, avg))

        # ---- for DataFrame ----
        rows_for_df.append({
            "player_id": player_id,
            "player_name": player_name,
            "format": fmt,
            "runs": runs,
            "batting_average": avg
        })

conn.commit()
cursor.close()
conn.close()

# ---------------------------
# CREATE DATAFRAME
# ---------------------------
df = pd.DataFrame(all_rows)

print(df.head())

   player_id format   runs  batting_average
0        576   Test   4301            40.58
1        576    ODI  11577            48.85
2        576   T20I   4231            31.34
3        576    IPL   7046            29.73
4        587   Test   4095            38.27

In [22]:
###
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/8733/batting"

headers = {
	"x-rapidapi-key": "ca8831ebb4mshc6fa8ff575d89aap1db4a1jsnc3cc6c6f77a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

batting_data = response.json()

In [23]:
batting_data.keys()

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [24]:
batting_data['headers']

['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL']

In [25]:
batting_data['values']

[{'values': ['Matches', '67', '94', '72', '145']},
 {'values': ['Innings', '118', '86', '68', '136']},
 {'values': ['Runs', '4053', '3360', '2265', '5222']},
 {'values': ['Balls', '7810', '3715', '1628', '3839']},
 {'values': ['Highest', '199', '112', '110', '132']},
 {'values': ['Average', '35.87', '50.91', '37.75', '46.21']},
 {'values': ['SR', '51.90', '90.45', '139.13', '136.03']},
 {'values': ['Not Out', '5', '20', '8', '23']},
 {'values': ['Fours', '484', '259', '191', '452']},
 {'values': ['Sixes', '30', '76', '99', '208']},
 {'values': ['Ducks', '9', '3', '5', '4']},
 {'values': ['50s', '20', '20', '22', '40']},
 {'values': ['100s', '11', '8', '2', '5']},
 {'values': ['200s', '0', '0', '0', '0']},
 {'values': ['300s', '0', '0', '0', '0']},
 {'values': ['400s', '0', '0', '0', '0']}]

In [26]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/24729/bowling"

headers = {
	"x-rapidapi-key": "ca8831ebb4mshc6fa8ff575d89aap1db4a1jsnc3cc6c6f77a4",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

bowling_data = response.json()

In [27]:
bowling_data.keys()

dict_keys(['headers', 'values', 'appIndex', 'seriesSpinner'])

In [28]:
bowling_data['headers']

['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL']

In [29]:
bowling_data['values']

[{'values': ['Matches', '2', '14', '9', '33']},
 {'values': ['Innings', '3', '14', '8', '32']},
 {'values': ['Balls', '270', '687', '168', '649']},
 {'values': ['Runs', '203', '712', '297', '1029']},
 {'values': ['Maidens', '6', '5', '1', '1']},
 {'values': ['Wickets', '4', '26', '9', '40']},
 {'values': ['Avg', '50.75', '27.38', '33.0', '25.73']},
 {'values': ['Eco', '4.51', '6.22', '10.61', '9.51']},
 {'values': ['SR', '67.5', '26.42', '18.67', '16.23']},
 {'values': ['BBI', '3/48', '4/39', '3/33', '3/24']},
 {'values': ['BBM', '4/117', '4/39', '3/33', '3/24']},
 {'values': ['4w', '0', '1', '0', '0']},
 {'values': ['5w', '0', '0', '0', '0']},
 {'values': ['10w', '0', '0', '0', '0']}]

In [51]:
import requests
import pandas as pd
import psycopg2
import time

# -------------------------------
# API CONFIG
# -------------------------------

API_KEY = "210732413emshccb12551b2a5344p108da8jsn8cdbeae08bc8"

HEADERS = {
    "x-rapidapi-key": API_KEY,
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

BASE_URL = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player"


# -------------------------------
# PLAYER IDS
# -------------------------------

player_ids = [
    576,587,1413,7915,8257,8271,8292,8683,8733,8808,
    9311,9428,9429,9647,9716,10276,10551,10636,10744,
    10754,10808,10896,10945,11195,11808,11813,12086,
    12926,13217,13866,13940,14504,14659,14691,14701,
    14726,24729
]


# -------------------------------
# DATABASE CONNECTION
# -------------------------------

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")


# -------------------------------
# CREATE TABLE
# -------------------------------

cursor.execute("""

CREATE TABLE IF NOT EXISTS player_performance (
    player_id BIGINT,
    format TEXT,
    matches INT,
    innings INT,
    runs INT,
    balls INT,
    batting_average FLOAT,
    strike_rate FLOAT,
    wickets INT,
    bowling_average FLOAT,
    economy FLOAT,
    PRIMARY KEY(player_id, format)

)

""")

conn.commit()


# -------------------------------
# API FETCH FUNCTIONS
# -------------------------------

def fetch_batting(player_id):

    url = f"{BASE_URL}/{player_id}/batting"

    response = requests.get(url, headers=HEADERS)

    if response.status_code != 200:
        print(f"Batting API failed for {player_id}", response.status_code)
        return None

    return response.json()


def fetch_bowling(player_id):

    url = f"{BASE_URL}/{player_id}/bowling"

    response = requests.get(url, headers=HEADERS)

    if response.status_code != 200:
        print(f"Bowling API failed for {player_id}", response.status_code)
        return None

    return response.json()


# -------------------------------
# JSON → DATAFRAME TRANSFORM
# -------------------------------

def transform_batting(player_id, batting_json):

    formats = ['Test','ODI','T20','IPL']

    values = batting_json['values']

    data = {}

    for row in values:
        metric = row['values'][0]
        data[metric] = row['values'][1:]

    df = pd.DataFrame(data)

    df['format'] = formats
    df['player_id'] = player_id

    df = df.rename(columns={
        'Matches':'matches',
        'Innings':'innings',
        'Runs':'runs',
        'Balls':'balls',
        'Average':'batting_average',
        'SR':'strike_rate'
    })

    return df[['player_id','format','matches','innings','runs','balls','batting_average','strike_rate']]


def transform_bowling(player_id, bowling_json):

    formats = ['Test','ODI','T20','IPL']

    values = bowling_json['values']

    data = {}

    for row in values:
        metric = row['values'][0]
        data[metric] = row['values'][1:]

    df = pd.DataFrame(data)

    df['format'] = formats
    df['player_id'] = player_id

    df = df.rename(columns={
        'Wickets':'wickets',
        'Avg':'bowling_average',
        'Eco':'economy'
    })

    return df[['player_id','format','wickets','bowling_average','economy']]


# -------------------------------
# MAIN LOOP
# -------------------------------

all_data = []

for player_id in player_ids:

    print("Processing player", player_id)

    batting_json = fetch_batting(player_id)
    bowling_json = fetch_bowling(player_id)

    if batting_json is None:
        continue

    batting_df = transform_batting(player_id, batting_json)

    if bowling_json:
        bowling_df = transform_bowling(player_id, bowling_json)

        merged_df = pd.merge(
            batting_df,
            bowling_df,
            on=['player_id','format'],
            how='left'
        )

    else:
        merged_df = batting_df

    all_data.append(merged_df)

    time.sleep(2)   # avoid rate limit


# -------------------------------
# FINAL DATAFRAME
# -------------------------------

final_df = pd.concat(all_data, ignore_index=True)

print(final_df.head())


# -------------------------------
# INSERT INTO POSTGRESQL
# -------------------------------

for _, row in final_df.iterrows():

    cursor.execute("""

    INSERT INTO player_performance
    (player_id,format,matches,innings,runs,balls,batting_average,strike_rate,wickets,bowling_average,economy)

    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

    ON CONFLICT (player_id,format)
    DO UPDATE SET
        runs = EXCLUDED.runs,
        wickets = EXCLUDED.wickets,
        batting_average = EXCLUDED.batting_average

    """,
    (
        row.player_id,
        row.format,
        row.matches,
        row.innings,
        row.runs,
        row.balls,
        row.batting_average,
        row.strike_rate,
        row.get('wickets'),
        row.get('bowling_average'),
        row.get('economy')
    ))

conn.commit()

print("Data inserted successfully!")

cursor.close()
conn.close()

Connected to DB
Processing player 576
Processing player 587
Processing player 1413
Processing player 7915
Processing player 8257
Processing player 8271
Processing player 8292
Processing player 8683
Processing player 8733
Processing player 8808
Processing player 9311
Processing player 9428
Processing player 9429
Processing player 9647
Processing player 9716
Processing player 10276
Processing player 10551
Processing player 10636
Processing player 10744
Processing player 10754
Processing player 10808
Processing player 10896
Processing player 10945
Processing player 11195
Processing player 11808
Processing player 11813
Processing player 12086
Processing player 12926
Processing player 13217
Processing player 13866
Processing player 13940
Processing player 14504
Processing player 14659
Processing player 14691
Processing player 14701
Processing player 14726
Processing player 24729
   player_id format matches innings   runs  balls batting_average strike_rate  \
0        576   Test      67     116   4301   7538           40.58       57.06
1        576    ODI     282     274  11577  12482           48.85       92.75
2        576    T20     159     151   4231   3003           31.34      140.90
3        576    IPL     272     267   7046   5334           29.73      132.10
4        587   Test      89     133   4095   7389           38.27       55.43

  wickets bowling_average economy
0       2           112.0    3.51
1       9           59.22    5.24
2       1           113.0    9.97
3      15            30.2    8.02
4     348           25.12    2.59
Data inserted successfully!

In [52]:
### 

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/team/2"

querystring = {"statsType":"mostRuns","year":"2020"}

headers = {
	"x-rapidapi-key": "210732413emshccb12551b2a5344p108da8jsn8cdbeae08bc8",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)

data = response.json()

In [53]:
data.keys()

dict_keys(['filter', 'headers', 'values', 'appIndex'])

In [54]:
data['headers']

['Batter', 'M', 'I', 'R', 'Avg']

In [55]:
data['values']

[{'values': ['1447', 'Ajinkya Rahane', '4', '8', '272', '38.86']},
 {'values': ['1448', 'Pujara', '4', '8', '163', '20.38']},
 {'values': ['2195', 'Mayank Agarwal', '4', '8', '133', '16.62']},
 {'values': ['8424', 'Hanuma Vihari', '4', '7', '131', '18.71']},
 {'values': ['1413', 'Virat Kohli', '3', '6', '116', '19.33']},
 {'values': ['12094', 'Prithvi Shaw', '3', '6', '102', '17.00']},
 {'values': ['10744', 'Rishabh Pant', '3', '5', '89', '17.80']},
 {'values': ['587', 'Ravindra Jadeja', '2', '3', '82', '41.00']},
 {'values': ['11808', 'Shubman Gill', '1', '2', '80', '80.00']},
 {'values': ['7909', 'Mohammed Shami', '3', '6', '45', '11.25']},
 {'values': ['1593', 'Ashwin', '3', '5', '33', '6.60']},
 {'values': ['9311', 'Jasprit Bumrah', '4', '7', '20', '5.00']},
 {'values': ['1858', 'Umesh', '3', '5', '20', '5.00']},
 {'values': ['702', 'Ishant Sharma', '1', '2', '17', '8.50']},
 {'values': ['1465', 'W Saha', '1', '2', '13', '6.50']}]

In [60]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/139478/scard"

headers = {
	"x-rapidapi-key": "210732413emshccb12551b2a5344p108da8jsn8cdbeae08bc8",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [61]:
data.keys()

dict_keys(['scorecard', 'ismatchcomplete', 'appindex', 'status', 'responselastupdated'])

In [62]:
data['scorecard']

[{'inningsid': 1,
  'batsman': [{'id': 8271,
    'balls': 42,
    'runs': 89,
    'fours': 8,
    'sixes': 7,
    'strkrate': '211.9',
    'name': 'Sanju Samson',
    'nickname': 'Sanju Samson',
    'iscaptain': False,
    'iskeeper': True,
    'outdec': 'c Phil Salt b Will Jacks',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 12086,
    'balls': 7,
    'runs': 9,
    'fours': 2,
    'sixes': 0,
    'strkrate': '128.57',
    'name': 'Abhishek Sharma',
    'nickname': 'Abhishek Sharma',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Phil Salt b Will Jacks',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 10276,
    'balls': 18,
    'runs': 39,
    'fours': 4,
    'sixes': 2,
    'strkrate': '216.67',
    'name': 'Ishan Kishan',
    'nickname': 'Ishan Kishan',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Will Jacks b Adil Rashid',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 11195,
    'balls': 25,
    'runs': 43,
    'fours': 1,
    'sixes': 4,
    'strkrate': '172',
    'name': 'Shivam Dube',
    'nickname': 'Shivam Dube',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'run out (Harry Brook)',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 7915,
    'balls': 6,
    'runs': 11,
    'fours': 0,
    'sixes': 1,
    'strkrate': '183.33',
    'name': 'Suryakumar Yadav',
    'nickname': 'Suryakumar Yadav',
    'iscaptain': True,
    'iskeeper': False,
    'outdec': 'st Jos Buttler b Adil Rashid',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 9647,
    'balls': 12,
    'runs': 27,
    'fours': 3,
    'sixes': 2,
    'strkrate': '225',
    'name': 'Hardik Pandya',
    'nickname': 'Hardik Pandya',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'run out (Jacob Bethell/Jos Buttler)',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 14504,
    'balls': 7,
    'runs': 21,
    'fours': 0,
    'sixes': 3,
    'strkrate': '300',
    'name': 'Tilak Varma',
    'nickname': 'Tilak Varma',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'b Jofra Archer',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8808,
    'balls': 2,
    'runs': 2,
    'fours': 0,
    'sixes': 0,
    'strkrate': '100',
    'name': 'Axar Patel',
    'nickname': 'Axar Patel',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 12926,
    'balls': 1,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Varun Chakaravarthy',
    'nickname': 'Varun Chakaravarthy',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 13217,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Arshdeep Singh',
    'nickname': 'Arshdeep Singh',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 9311,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Jasprit Bumrah',
    'nickname': 'Jasprit Bumrah',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''}],
  'bowler': [{'id': 11540,
    'overs': '4',
    'maidens': 0,
    'wickets': 1,
    'runs': 61,
    'economy': '15.2',
    'name': 'Jofra Archer',
    'nickname': 'Jofra Archer',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 12258,
    'overs': '4',
    'maidens': 0,
    'wickets': 2,
    'runs': 40,
    'economy': '10',
    'name': 'Will Jacks',
    'nickname': 'Will Jacks',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8512,
    'overs': '3',
    'maidens': 0,
    'wickets': 0,
    'runs': 36,
    'economy': '12',
    'name': 'Jamie Overton',
    'nickname': 'Jamie Overton',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 18,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': 'IN'},
   {'id': 10420,
    'overs': '4',
    'maidens': 0,
    'wickets': 0,
    'runs': 53,
    'economy': '13.2',
    'name': 'Sam Curran',
    'nickname': 'Sam Curran',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1742,
    'overs': '4',
    'maidens': 0,
    'wickets': 2,
    'runs': 41,
    'economy': '10.2',
    'name': 'Adil Rashid',
    'nickname': 'Adil Rashid',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 6639,
    'overs': '1',
    'maidens': 0,
    'wickets': 0,
    'runs': 19,
    'economy': '19',
    'name': 'Liam Dawson',
    'nickname': 'Liam Dawson',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 6,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''}],
  'fow': {'fow': [{'batsmanid': 12086,
     'batsmanname': 'Abhishek Sharma',
     'overnbr': 1.6,
     'runs': 20,
     'ballnbr': 12},
    {'batsmanid': 10276,
     'batsmanname': 'Ishan Kishan',
     'overnbr': 9.3,
     'runs': 117,
     'ballnbr': 57},
    {'batsmanid': 8271,
     'batsmanname': 'Sanju Samson',
     'overnbr': 13.1,
     'runs': 160,
     'ballnbr': 79},
    {'batsmanid': 7915,
     'batsmanname': 'Suryakumar Yadav',
     'overnbr': 15.4,
     'runs': 190,
     'ballnbr': 94},
    {'batsmanid': 11195,
     'batsmanname': 'Shivam Dube',
     'overnbr': 17.3,
     'runs': 212,
     'ballnbr': 105},
    {'batsmanid': 14504,
     'batsmanname': 'Tilak Varma',
     'overnbr': 18.5,
     'runs': 236,
     'ballnbr': 113},
    {'batsmanid': 9647,
     'batsmanname': 'Hardik Pandya',
     'overnbr': 19.5,
     'runs': 251,
     'ballnbr': 119}]},
  'extras': {'legbyes': 1,
   'byes': 2,
   'wides': 9,
   'noballs': 0,
   'penalty': 0,
   'total': 12},
  'pp': {'powerplay': [{'id': 19,
     'ovrfrom': 0.1,
     'ovrto': 6.0,
     'pptype': 'Mandatory',
     'run': 67,
     'wickets': 0}]},
  'score': 253,
  'wickets': 7,
  'overs': 20.0,
  'runrate': 12.65,
  'batteamname': 'India',
  'batteamsname': 'IND',
  'isdeclared': False,
  'isfollowon': False,
  'ballnbr': 120,
  'rpb': 2.11,
  'partnership': {'partnership': [{'id': 0,
     'bat1id': 8271,
     'bat1name': 'Sanju Samson',
     'bat1runs': 11,
     'bat1fours': 1,
     'bat1sixes': 1,
     'bat2id': 12086,
     'bat2name': 'Abhishek Sharma',
     'bat2runs': 9,
     'bat2fours': 2,
     'bat2sixes': 0,
     'totalruns': 20,
     'totalballs': 12,
     'bat1balls': 5,
     'bat2balls': 7,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 1,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 1,
     'bat1sixers': 1,
     'bat2ones': 1,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 2,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 8271,
     'bat1name': 'Sanju Samson',
     'bat1runs': 55,
     'bat1fours': 7,
     'bat1sixes': 3,
     'bat2id': 10276,
     'bat2name': 'Ishan Kishan',
     'bat2runs': 39,
     'bat2fours': 4,
     'bat2sixes': 2,
     'totalruns': 97,
     'totalballs': 45,
     'bat1balls': 27,
     'bat2balls': 18,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 9,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 7,
     'bat1sixers': 3,
     'bat2ones': 7,
     'bat2twos': 2,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 4,
     'bat2sixers': 2},
    {'id': 0,
     'bat1id': 8271,
     'bat1name': 'Sanju Samson',
     'bat1runs': 23,
     'bat1fours': 0,
     'bat1sixes': 3,
     'bat2id': 11195,
     'bat2name': 'Shivam Dube',
     'bat2runs': 18,
     'bat2fours': 0,
     'bat2sixes': 2,
     'totalruns': 43,
     'totalballs': 22,
     'bat1balls': 10,
     'bat2balls': 12,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 5,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 3,
     'bat2ones': 6,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 2},
    {'id': 0,
     'bat1id': 7915,
     'bat1name': 'Suryakumar Yadav',
     'bat1runs': 11,
     'bat1fours': 0,
     'bat1sixes': 1,
     'bat2id': 11195,
     'bat2name': 'Shivam Dube',
     'bat2runs': 17,
     'bat2fours': 1,
     'bat2sixes': 1,
     'totalruns': 30,
     'totalballs': 15,
     'bat1balls': 6,
     'bat2balls': 9,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 3,
     'bat1twos': 1,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 1,
     'bat2ones': 5,
     'bat2twos': 1,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 1,
     'bat2sixers': 1},
    {'id': 0,
     'bat1id': 9647,
     'bat1name': 'Hardik Pandya',
     'bat1runs': 13,
     'bat1fours': 3,
     'bat1sixes': 0,
     'bat2id': 11195,
     'bat2name': 'Shivam Dube',
     'bat2runs': 8,
     'bat2fours': 0,
     'bat2sixes': 1,
     'totalruns': 22,
     'totalballs': 11,
     'bat1balls': 7,
     'bat2balls': 4,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 1,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 3,
     'bat1sixers': 0,
     'bat2ones': 2,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 1},
    {'id': 0,
     'bat1id': 9647,
     'bat1name': 'Hardik Pandya',
     'bat1runs': 1,
     'bat1fours': 0,
     'bat1sixes': 0,
     'bat2id': 14504,
     'bat2name': 'Tilak Varma',
     'bat2runs': 21,
     'bat2fours': 0,
     'bat2sixes': 3,
     'totalruns': 24,
     'totalballs': 8,
     'bat1balls': 1,
     'bat2balls': 7,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 1,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 1,
     'bat2twos': 1,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 3},
    {'id': 0,
     'bat1id': 9647,
     'bat1name': 'Hardik Pandya',
     'bat1runs': 12,
     'bat1fours': 0,
     'bat1sixes': 2,
     'bat2id': 8808,
     'bat2name': 'Axar Patel',
     'bat2runs': 2,
     'bat2fours': 0,
     'bat2sixes': 0,
     'totalruns': 14,
     'totalballs': 6,
     'bat1balls': 4,
     'bat2balls': 2,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 2,
     'bat2ones': 2,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 12926,
     'bat1name': 'Varun Chakaravarthy',
     'bat1runs': 0,
     'bat1fours': 0,
     'bat1sixes': 0,
     'bat2id': 8808,
     'bat2name': 'Axar Patel',
     'bat2runs': 0,
     'bat2fours': 0,
     'bat2sixes': 0,
     'totalruns': 2,
     'totalballs': 1,
     'bat1balls': 1,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0}]}},
 {'inningsid': 2,
  'batsman': [{'id': 10479,
    'balls': 3,
    'runs': 5,
    'fours': 1,
    'sixes': 0,
    'strkrate': '166.67',
    'name': 'Philip Salt',
    'nickname': 'Phil Salt',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Axar Patel b Hardik Pandya',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 2258,
    'balls': 17,
    'runs': 25,
    'fours': 4,
    'sixes': 1,
    'strkrate': '147.06',
    'name': 'Jos Buttler',
    'nickname': 'Jos Buttler',
    'iscaptain': False,
    'iskeeper': True,
    'outdec': 'b Varun Chakaravarthy',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 12201,
    'balls': 6,
    'runs': 7,
    'fours': 1,
    'sixes': 0,
    'strkrate': '116.67',
    'name': 'Harry Brook',
    'nickname': 'Harry Brook',
    'iscaptain': True,
    'iskeeper': False,
    'outdec': 'c Axar Patel b Jasprit Bumrah',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 19636,
    'balls': 48,
    'runs': 105,
    'fours': 8,
    'sixes': 7,
    'strkrate': '218.75',
    'name': 'Jacob Bethell',
    'nickname': 'Jacob Bethell',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'run out (Hardik Pandya/Sanju Samson)',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 12254,
    'balls': 5,
    'runs': 17,
    'fours': 1,
    'sixes': 2,
    'strkrate': '340',
    'name': 'Tom Banton',
    'nickname': 'Tom Banton',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'b Axar Patel',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 12258,
    'balls': 20,
    'runs': 35,
    'fours': 4,
    'sixes': 2,
    'strkrate': '175',
    'name': 'Will Jacks',
    'nickname': 'Will Jacks',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Shivam Dube b Arshdeep Singh',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 10420,
    'balls': 14,
    'runs': 18,
    'fours': 2,
    'sixes': 0,
    'strkrate': '128.57',
    'name': 'Sam Curran',
    'nickname': 'Sam Curran',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Tilak Varma b Hardik Pandya',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8512,
    'balls': 3,
    'runs': 2,
    'fours': 0,
    'sixes': 0,
    'strkrate': '66.67',
    'name': 'Jamie Overton',
    'nickname': 'Jamie Overton',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': 'IN'},
   {'id': 11540,
    'balls': 4,
    'runs': 19,
    'fours': 0,
    'sixes': 3,
    'strkrate': '475',
    'name': 'Jofra Archer',
    'nickname': 'Jofra Archer',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 6639,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Liam Dawson',
    'nickname': 'Liam Dawson',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,

In [63]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "210732413emshccb12551b2a5344p108da8jsn8cdbeae08bc8",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [64]:
data.keys()

dict_keys(['typeMatches', 'filters', 'appIndex', 'responseLastUpdated'])

In [65]:
data['typeMatches']

[{'matchType': 'International',
  'seriesMatches': [{'seriesAdWrapper': {'seriesId': 11253,
     'seriesName': "ICC Men's T20 World Cup 2026",
     'matches': [{'matchInfo': {'matchId': 139478,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '2nd Semi-Final',
        'matchFormat': 'T20',
        'startDate': '1772717400000',
        'endDate': '1772730000000',
        'state': 'Complete',
        'status': 'India won by 7 runs',
        'team1': {'teamId': 2,
         'teamName': 'India',
         'teamSName': 'IND',
         'imageId': 776162},
        'team2': {'teamId': 9,
         'teamName': 'England',
         'teamSName': 'ENG',
         'imageId': 776237},
        'venueInfo': {'id': 81,
         'ground': 'Wankhede Stadium',
         'city': 'Mumbai',
         'timezone': '+05:30',
         'latitude': '18.938956',
         'longitude': '72.825719'},
        'currBatTeamId': 2,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'IND Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 253,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 246,
          'wickets': 7,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 139472,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '1st Semi-Final',
        'matchFormat': 'T20',
        'startDate': '1772631000000',
        'endDate': '1772643600000',
        'state': 'Complete',
        'status': 'New Zealand won by 9 wkts',
        'team1': {'teamId': 11,
         'teamName': 'South Africa',
         'teamSName': 'RSA',
         'imageId': 776287},
        'team2': {'teamId': 13,
         'teamName': 'New Zealand',
         'teamSName': 'NZ',
         'imageId': 776333},
        'venueInfo': {'id': 31,
         'ground': 'Eden Gardens',
         'city': 'Kolkata',
         'timezone': '+05:30',
         'latitude': '22.564527',
         'longitude': '88.343247'},
        'currBatTeamId': 13,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'NZ Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 169,
          'wickets': 8,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 173,
          'wickets': 1,
          'overs': 12.5}}}},
      {'matchInfo': {'matchId': 139461,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '52nd Match, Super 8 Group 1 (X1 v X3)',
        'matchFormat': 'T20',
        'startDate': '1772371800000',
        'endDate': '1772384400000',
        'state': 'Complete',
        'status': 'India won by 5 wkts',
        'team1': {'teamId': 10,
         'teamName': 'West Indies',
         'teamSName': 'WI',
         'imageId': 776191},
        'team2': {'teamId': 2,
         'teamName': 'India',
         'teamSName': 'IND',
         'imageId': 776162},
        'venueInfo': {'id': 31,
         'ground': 'Eden Gardens',
         'city': 'Kolkata',
         'timezone': '+05:30',
         'latitude': '22.564527',
         'longitude': '88.343247'},
        'currBatTeamId': 2,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'IND Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 195,
          'wickets': 4,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 199,
          'wickets': 5,
          'overs': 19.2}}}},
      {'matchInfo': {'matchId': 139450,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '51st Match, Super 8 Group 1 (X2 v X4)',
        'matchFormat': 'T20',
        'startDate': '1772357400000',
        'endDate': '1772370000000',
        'state': 'Complete',
        'status': 'South Africa won by 5 wkts',
        'team1': {'teamId': 12,
         'teamName': 'Zimbabwe',
         'teamSName': 'ZIM',
         'imageId': 776198},
        'team2': {'teamId': 11,
         'teamName': 'South Africa',
         'teamSName': 'RSA',
         'imageId': 776287},
        'venueInfo': {'id': 51,
         'ground': 'Arun Jaitley Stadium',
         'city': 'Delhi',
         'timezone': '+05:30',
         'latitude': '28.637891',
         'longitude': '77.243073'},
        'currBatTeamId': 11,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'RSA Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 153,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 154,
          'wickets': 5,
          'overs': 17.5}}}},
      {'matchInfo': {'matchId': 139448,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '50th Match, Super 8 Group 2 (Y3 v Y4)',
        'matchFormat': 'T20',
        'startDate': '1772285400000',
        'endDate': '1772298000000',
        'state': 'Complete',
        'status': 'Pakistan won by 5 runs',
        'team1': {'teamId': 3,
         'teamName': 'Pakistan',
         'teamSName': 'PAK',
         'imageId': 776308},
        'team2': {'teamId': 5,
         'teamName': 'Sri Lanka',
         'teamSName': 'SL',
         'imageId': 776254},
        'venueInfo': {'id': 254,
         'ground': 'Pallekele International Cricket Stadium',
         'city': 'Pallekele',
         'timezone': '+05:30',
         'latitude': '7.280691',
         'longitude': '80.722493'},
        'currBatTeamId': 3,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'PAK Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 212,
          'wickets': 8,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 207,
          'wickets': 6,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 139437,
        'seriesId': 11253,
        'seriesName': "ICC Men's T20 World Cup 2026",
        'matchDesc': '49th Match, Super 8 Group 2 (Y1 v Y2)',
        'matchFormat': 'T20',
        'startDate': '1772199000000',
        'endDate': '1772211600000',
        'state': 'Complete',
        'status': 'England won by 4 wkts',
        'team1': {'teamId': 13,
         'teamName': 'New Zealand',
         'teamSName': 'NZ',
         'imageId': 776333},
        'team2': {'teamId': 9,
         'teamName': 'England',
         'teamSName': 'ENG',
         'imageId': 776237},
        'venueInfo': {'id': 15,
         'ground': 'R.Premadasa Stadium',
         'city': 'Colombo',
         'timezone': '+05:30',
         'latitude': '6.939966',
         'longitude': '79.872222'},
        'currBatTeamId': 9,
        'seriesStartDt': '1770422400000',
        'seriesEndDt': '1773100800000',
        'isTimeAnnounced': True,
        'stateTitle': 'ENG Won',
        'isFantasyEnabled': True},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 159,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 161,
          'wickets': 6,
          'overs': 19.3}}}}]}},
   {'seriesAdWrapper': {'seriesId': 11542,
     'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
     'matches': [{'matchInfo': {'matchId': 147016,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': 'Final',
        'matchFormat': 'T20',
        'startDate': '1772260200000',
        'endDate': '1772272800000',
        'state': 'Complete',
        'status': 'Match tied (Bahrain won the super over)',
        'team1': {'teamId': 547,
         'teamName': 'Japan',
         'teamSName': 'JPN',
         'imageId': 248418},
        'team2': {'teamId': 543,
         'teamName': 'Bahrain',
         'teamSName': 'BHR',
         'imageId': 172594},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'Complete'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 108,
          'wickets': 9,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 108,
          'wickets': 9,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 147005,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '3rd place play-off',
        'matchFormat': 'T20',
        'startDate': '1772244000000',
        'endDate': '1772256600000',
        'state': 'Complete',
        'status': 'Bhutan won by 7 runs',
        'team1': {'teamId': 555,
         'teamName': 'Bhutan',
         'teamSName': 'BTN',
         'imageId': 172607},
        'team2': {'teamId': 384,
         'teamName': 'Thailand',
         'teamSName': 'THAI',
         'imageId': 172437},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 555,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'BTN Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 86,
          'wickets': 8,
          'overs': 12.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 79,
          'wickets': 9,
          'overs': 12.6}}}},
      {'matchInfo': {'matchId': 146994,
        'seriesId': 11542,
        'seriesName': 'Quadrangular T20I Series in Thailand 2026 ',
        'matchDesc': '6th Match',
        'matchFormat': 'T20',
        'startDate': '1772173800000',
        'endDate': '1772186400000',
        'state': 'Complete',
        'status': 'Bahrain won by 12 runs',
        'team1': {'teamId': 543,
         'teamName': 'Bahrain',
         'teamSName': 'BHR',
         'imageId': 172594},
        'team2': {'teamId': 384,
         'teamName': 'Thailand',
         'teamSName': 'THAI',
         'imageId': 172437},
        'venueInfo': {'id': 474,
         'ground': 'Terdthai Cricket Ground',
         'city': 'Bangkok',
         'timezone': '+07:00',
         'latitude': '13.756331',
         'longitude': '100.501765'},
        'currBatTeamId': 543,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'BHR Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 126,
          'wickets': 7,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 114,
          'wickets': 10,
          'overs': 19.3}}}}]}},
   {'seriesAdWrapper': {'seriesId': 11581,
     'seriesName': 'Kuwait tour of Hong Kong, China, 2026',
     'matches': [{'matchInfo': {'matchId': 147733,
        'seriesId': 11581,
        'seriesName': 'Kuwait tour of Hong Kong, China, 2026',
        'matchDesc': '4th T20I',
        'matchFormat': 'T20',
        'startDate': '1772342100000',
        'endDate': '1772354700000',
        'state': 'Complete',
        'status': 'Kuwait won by 3 wkts',
        'team1': {'teamId': 8,
         'teamName': 'Hong Kong, China',
         'teamSName': 'HKC',
         'imageId': 776271},
        'team2': {'teamId': 298,
         'teamName': 'Kuwait',
         'teamSName': 'KUW',
         'imageId': 776312},
        'venueInfo': {'id': 454,
         'ground': 'Mission Road Ground',
         'city': 'Mong Kok',
         'timezone': '+08:00',
         'latitude': '22.323286',
         'longitude': '114.1828583'},
        'currBatTeamId': 298,
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772496000000',
        'isTimeAnnounced': True,
        'stateTitle': 'KUW Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 125,
          'wickets': 9,
          'overs': 19.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 127,
          'wickets': 7,
          'overs': 18.5}}}},
      {'matchInfo': {'matchId': 147722,
        'seriesId': 11581,
        'seriesName': 'Kuwait tour of Hong Kong, China, 2026',
        'matchDesc': '3rd T20I',
        'matchFormat': 'T20',
        'startDate': '1772255700000',
        'endDate': '1772268300000',
        'state': 'Complete',
        'status': 'Match abandoned without a ball bowled (No toss)',
        'team1': {'teamId': 8,
         'teamName': 'Hong Kong, China',
         'teamSName': 'HKC',
         'imageId': 776271},
        'team2': {'teamId': 298,
         'teamName': 'Kuwait',
         'teamSName': 'KUW',
         'imageId': 776312},
        'venueInfo': {'id': 454,
         'ground': 'Mission Road Ground',
         'city': 'Mong Kok',
         'timezone': '+08:00',
         'latitude': '22.323286',
         'longitude': '114.1828583'},
        'seriesStartDt': '1771977600000',
        'seriesEndDt': '1772496000000',
        'isTimeAnnounced': True,
        'stateTitle': 'Abandon'}}]}},
   {'ad': {'name': 'native_matches',
     'layout': 'native_large',
     'position': 3}}]},
 {'matchType': 'Domestic',
  'seriesMatches': [{'seriesAdWrapper': {'seriesId': 10317,
     'seriesName': 'Ranji Trophy Elite 2025-26',
     'matches': [{'matchInfo': {'matchId': 125085,
        'seriesId': 10317,
        'seriesName': 'Ranji Trophy Elite 2025-26',
        'matchDesc': 'Final',
        'matchFormat': 'TEST',
        'startDate': '1771905600000',
        'endDate': '1772276400000',
        'state': 'Complete',
        'status': 'Match drawn',
        'team1': {'teamId': 252,
         'teamName': 'Jammu and Kashmir',
         'teamSName': 'JK',
         'imageId': 172305},
        'team2': {'teamId': 128,
         'teamName': 'Karnataka',
         'teamSName': 'KAR',
         'imageId': 776345},
        'venueInfo': {'id': 329,
         'ground': 'KSCA Hubli Cricket Ground',
         'city': 'Hubli',
         'timezone': '+05:30',
         'latitude': '15.370228',
         'longitude': '75.127888'},
        'seriesStartDt': '1760486400000',
        'seriesEndDt': '1772409600000',
        'isTimeAnnounced': True,
        'stateTitle': 'Complete'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 584,
          'wickets': 10,
          'overs': 173.1},
         'inngs2': {'inningsId': 3,
          'runs': 342,
          'wickets': 4,
          'overs': 112.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 293,
          'wickets': 10,
          'overs': 93.3}}}}]}},
   {'seriesAdWrapper': {'seriesId': 11553,
     'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
     'matches': [{'matchInfo': {'matchId': 147123,
        'seriesId': 11553,
        'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
        'matchDesc': '8th Match',
        'matchFormat': 'ODI',
        'startDate': '1772708400000',
        'endDate': '1772737200000',
        'state': 'Complete',
        'status': 'Dolphins won by 12 runs  -  2nd Inns reduced to 20 Ovs, DLS Target 165',
        'team1': {'teamId': 90,
         'teamName': 'Dolphins',
         'teamSName': 'DOL',
         'imageId': 172183},
        'team2': {'teamId': 89,
         'teamName': 'Titans',
         'teamSName': 'TIT',
         'imageId': 172182},
        'venueInfo': {'id': 74,
         'ground': 'Kingsmead',
         'city': 'Durban',
         'timezone': '+02:00',
         'latitude': '-29.850018',
         'longitude': '31.027888'},
        'currBatTeamId': 90,
        'seriesStartDt': '1772150400000',
        'seriesEndDt': '1774915200000',
        'isTimeAnnounced': True,
        'stateTitle': 'DOL Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 281,
          'wickets': 9,
          'overs': 49.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 152,
          'wickets': 9,
          'overs': 19.6}}}},
      {'matchInfo': {'matchId': 147104,
        'seriesId': 11553,
        'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
        'matchDesc': '6th Match',
        'matchFormat': 'ODI',
        'startDate': '1772622000000',
        'endDate': '1772650800000',
        'state': 'Complete',
        'status': 'Boland won by 43 runs',
        'team1': {'teamId': 1759,
         'teamName': 'Boland',
         'teamSName': 'BOL',
         'imageId': 349610},
        'team2': {'teamId': 1766,
         'teamName': 'KwaZulu-Natal Inland - Tuskers',
         'teamSName': 'KZNIN',
         'imageId': 349611},
        'venueInfo': {'id': 207,
         'ground': 'Boland Park',
         'city': 'Paarl',
         'timezone': '+02:00',
         'latitude': '-33.730900',
         'longitude': '18.970760'},
        'currBatTeamId': 1759,
        'seriesStartDt': '1772150400000',
        'seriesEndDt': '1774915200000',
        'isTimeAnnounced': True,
        'stateTitle': 'BOL Won'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 224,
          'wickets': 9,
          'overs': 49.6}},
        'team2Score': {'inngs1': {'inningsId': 2,
          'runs': 181,
          'wickets': 10,
          'overs': 44.2}}}},
      {'matchInfo': {'matchId': 147112,
        'seriesId': 11553,
        'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
        'matchDesc': '7th Match',
        'matchFormat': 'ODI',
        'startDate': '1772622000000',
        'endDate': '1772650800000',
        'state': 'Complete',
        'status': 'No result  -  due to rain',
        'team1': {'teamId': 157,
         'teamName': 'Lions',
         'teamSName': 'LIONS',
         'imageId': 172224},
        'team2': {'teamId': 922,
         'teamName': 'North West - Eastvaal Renault Dragons',
         'teamSName': 'NWEST',
         'imageId': 248439},
        'venueInfo': {'id': 102,
         'ground': 'Senwes Park',
         'city': 'Potchefstroom',
         'timezone': '+02:00',
         'latitude': '-26.695565',
         'longitude': '27.100691'},
        'seriesStartDt': '1772150400000',
        'seriesEndDt': '1774915200000',
        'isTimeAnnounced': True,
        'stateTitle': 'Complete'},
       'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
          'runs': 229,
          'wickets': 3,
          'overs': 41.6}}}},
      {'matchInfo': {'matchId': 147093,
        'seriesId': 11553,
        'seriesName': 'CSA Provincial One-Day Challenge Division One 2026',
        'matchDesc': '5th Match',
        'matchFormat': 'ODI',
        'startDate': '1772535600000',
        'endDate': '1772564400000',
        'state': 'Complete',
        'status': 'Warriors won by 5 wkts',
        'team1': {'teamId': 917,
         'teamName': 'Western Province',
         'teamSName': 'WPR',
         'imageId': 248460},
        'team2': {'teamId': 155,
         'teamName': 'Warriors',
         'teamSName': 'WAR',
         'imageId': 172222},
        'venueInfo': {'id': 52,

In [ ]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/3213"

headers = {
	"x-rapidapi-key": "210732413emshccb12551b2a5344p108da8jsn8cdbeae08bc8",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [67]:
data.keys()

dict_keys(['matchDetails', 'appIndex'])

In [68]:
data['matchDetails']

[{'matchDetailsMap': {'key': 'Fri, 27 Nov 2020',
   'match': [{'matchInfo': {'matchId': 31633,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '1st ODI',
      'matchFormat': 'ODI',
      'startDate': '1606448400000',
      'endDate': '1606448400000',
      'state': 'complete',
      'status': 'Australia won by 66 runs',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Sydney Cricket Ground',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 4,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 374,
        'wickets': 6,
        'overs': 50.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 308,
        'wickets': 8,
        'overs': 50.0}}}}],
   'seriesId': 3213}},
 {'adDetail': {'name': 'native_news_index_random_1',
   'layout': 'native_large',
   'position': 1}},
 {'matchDetailsMap': {'key': 'Sun, 29 Nov 2020',
   'match': [{'matchInfo': {'matchId': 31638,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '2nd ODI',
      'matchFormat': 'ODI',
      'startDate': '1606621200000',
      'endDate': '1606621200000',
      'state': 'complete',
      'status': 'Australia won by 51 runs',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Sydney Cricket Ground',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 4,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 389,
        'wickets': 4,
        'overs': 50.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 338,
        'wickets': 9,
        'overs': 50.0}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Wed, 02 Dec 2020',
   'match': [{'matchInfo': {'matchId': 31643,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '3rd ODI',
      'matchFormat': 'ODI',
      'startDate': '1606880400000',
      'endDate': '1606880400000',
      'state': 'complete',
      'status': 'India won by 13 runs',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Manuka Oval',
       'city': 'Canberra',
       'timezone': '+11:00'},
      'currBatTeamId': 2,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 289,
        'wickets': 10,
        'overs': 49.3}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 302,
        'wickets': 5,
        'overs': 50.0}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Fri, 04 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30540,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '1st T20I',
      'matchFormat': 'T20',
      'startDate': '1607069400000',
      'endDate': '1607069400000',
      'state': 'complete',
      'status': 'India won by 11 runs',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Manuka Oval',
       'city': 'Canberra',
       'timezone': '+11:00'},
      'currBatTeamId': 2,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 150,
        'wickets': 7,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 161,
        'wickets': 7,
        'overs': 20.0}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Sun, 06 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30544,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '2nd T20I',
      'matchFormat': 'T20',
      'startDate': '1607242200000',
      'endDate': '1607242200000',
      'state': 'complete',
      'status': 'India won by 6 wkts',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Sydney Cricket Ground',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 2,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 194,
        'wickets': 5,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 195,
        'wickets': 4,
        'overs': 19.4}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Sun, 06 Dec 2020 - Tue, 08 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30549,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '1st Practice match',
      'matchFormat': 'TEST',
      'startDate': '1607211000000',
      'endDate': '1607383800000',
      'state': 'complete',
      'status': 'Match drawn',
      'team1': {'teamId': 79,
       'teamName': 'AUSTRALIA A',
       'teamSName': 'AUSA',
       'imageId': 776204},
      'team2': {'teamId': 78,
       'teamName': 'INDIA A',
       'teamSName': 'INDA',
       'imageId': 776181},
      'venueInfo': {'ground': 'Drummoyne Oval',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 79,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 306,
        'wickets': 9,
        'overs': 95.0,
        'isDeclared': True},
       'inngs2': {'inningsId': 4, 'runs': 52, 'wickets': 1, 'overs': 15.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 247,
        'wickets': 9,
        'overs': 93.0,
        'isDeclared': True},
       'inngs2': {'inningsId': 3,
        'runs': 189,
        'wickets': 9,
        'overs': 61.0,
        'isDeclared': True}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Tue, 08 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30545,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '3rd T20I',
      'matchFormat': 'T20',
      'startDate': '1607415000000',
      'endDate': '1607415000000',
      'state': 'complete',
      'status': 'Australia won by 12 runs',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Sydney Cricket Ground',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 4,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 186,
        'wickets': 5,
        'overs': 20.0}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 174,
        'wickets': 7,
        'overs': 20.0}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Fri, 11 Dec 2020 - Sun, 13 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30550,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '2nd Practice match',
      'matchFormat': 'TEST',
      'startDate': '1607657400000',
      'endDate': '1607830200000',
      'state': 'complete',
      'status': 'Match drawn',
      'team1': {'teamId': 79,
       'teamName': 'AUSTRALIA A',
       'teamSName': 'AUSA',
       'imageId': 776204},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Sydney Cricket Ground',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 79,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 108,
        'wickets': 10,
        'overs': 32.2},
       'inngs2': {'inningsId': 4, 'runs': 307, 'wickets': 4, 'overs': 75.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 194,
        'wickets': 10,
        'overs': 48.3},
       'inngs2': {'inningsId': 3,
        'runs': 386,
        'wickets': 4,
        'overs': 90.0,
        'isDeclared': True}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Thu, 17 Dec 2020 - Mon, 21 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30554,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '1st Test',
      'matchFormat': 'TEST',
      'startDate': '1608177600000',
      'endDate': '1608523200000',
      'state': 'complete',
      'status': 'Australia won by 8 wkts',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Adelaide Oval',
       'city': 'Adelaide',
       'timezone': '+10:30'},
      'currBatTeamId': 4,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
        'runs': 191,
        'wickets': 10,
        'overs': 72.1},
       'inngs2': {'inningsId': 4, 'runs': 93, 'wickets': 2, 'overs': 21.0}},
      'team2Score': {'inngs1': {'inningsId': 1,
        'runs': 244,
        'wickets': 10,
        'overs': 93.1},
       'inngs2': {'inningsId': 3, 'runs': 36, 'wickets': 9, 'overs': 21.2}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Sat, 26 Dec 2020 - Wed, 30 Dec 2020',
   'match': [{'matchInfo': {'matchId': 30555,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '2nd Test',
      'matchFormat': 'TEST',
      'startDate': '1608939000000',
      'endDate': '1609284600000',
      'state': 'complete',
      'status': 'India won by 8 wkts',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Melbourne Cricket Ground',
       'city': 'Melbourne',
       'timezone': '+11:00'},
      'currBatTeamId': 2,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 195,
        'wickets': 10,
        'overs': 72.3},
       'inngs2': {'inningsId': 3, 'runs': 200, 'wickets': 10, 'overs': 103.1}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 326,
        'wickets': 10,
        'overs': 115.1},
       'inngs2': {'inningsId': 4, 'runs': 70, 'wickets': 2, 'overs': 15.5}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Thu, 07 Jan 2021 - Mon, 11 Jan 2021',
   'match': [{'matchInfo': {'matchId': 31647,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '3rd Test',
      'matchFormat': 'TEST',
      'startDate': '1609975800000',
      'endDate': '1610321400000',
      'state': 'complete',
      'status': 'Match drawn',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'Sydney Cricket Ground',
       'city': 'Sydney',
       'timezone': '+11:00'},
      'currBatTeamId': 2,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 338,
        'wickets': 10,
        'overs': 105.4},
       'inngs2': {'inningsId': 3,
        'runs': 312,
        'wickets': 6,
        'overs': 87.0,
        'isDeclared': True}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 244,
        'wickets': 10,
        'overs': 100.4},
       'inngs2': {'inningsId': 4,
        'runs': 334,
        'wickets': 5,
        'overs': 131.0}}}}],
   'seriesId': 3213}},
 {'matchDetailsMap': {'key': 'Fri, 15 Jan 2021 - Tue, 19 Jan 2021',
   'match': [{'matchInfo': {'matchId': 31648,
      'seriesId': 3213,
      'seriesName': 'India tour of Australia, 2020-21',
      'matchDesc': '4th Test',
      'matchFormat': 'TEST',
      'startDate': '1610668800000',
      'endDate': '1611014400000',
      'state': 'complete',
      'status': 'India won by 3 wkts',
      'team1': {'teamId': 4,
       'teamName': 'AUSTRALIA',
       'teamSName': 'AUS',
       'imageId': 776202},
      'team2': {'teamId': 2,
       'teamName': 'INDIA',
       'teamSName': 'IND',
       'imageId': 776162},
      'venueInfo': {'ground': 'The Gabba',
       'city': 'Brisbane',
       'timezone': '+10:00'},
      'currBatTeamId': 2,
      'isTimeAnnounced': True},
     'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
        'runs': 369,
        'wickets': 10,
        'overs': 115.2},
       'inngs2': {'inningsId': 3, 'runs': 294, 'wickets': 10, 'overs': 75.5}},
      'team2Score': {'inngs1': {'inningsId': 2,
        'runs': 336,
        'wickets': 10,
        'overs': 111.4},
       'inngs2': {'inningsId': 4,
        'runs': 329,
        'wickets': 7,
        'overs': 97.0}}}}],
   'seriesId': 3213}}]

In [105]:
import requests
import json
import time

API_KEY = "c9de7c19b5msh7ab8030188091afp1f2e9cjsn5af11208b161"

headers = {
    "x-rapidapi-key": API_KEY,
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

series_ids = [3213, 3656, 4905, 6857, 7745, 9638]

for series_id in series_ids:

    print(f"Fetching matches for series {series_id}")

    url = f"https://cricbuzz-cricket.p.rapidapi.com/series/v1/{series_id}"

    response = requests.get(url, headers=headers)

    if response.status_code != 200:
        print(f"Error {response.status_code} for series {series_id}")
        continue

    data = response.json()

    file_name = f"series_{series_id}.json"

    with open(file_name, "w") as f:
        json.dump(data, f, indent=2)

    print(f"Saved {file_name}")

    # wait to avoid rate limit
    time.sleep(3)

print("All series responses saved.")

Fetching matches for series 3213
Saved series_3213.json
Fetching matches for series 3656
Saved series_3656.json
Fetching matches for series 4905
Saved series_4905.json
Fetching matches for series 6857
Saved series_6857.json
Fetching matches for series 7745
Saved series_7745.json
Fetching matches for series 9638
Saved series_9638.json
All series responses saved.

In [118]:
import requests
import pandas as pd
from datetime import datetime
import time

series_ids = [3213, 3656, 4905, 6857, 7745, 9638]

all_matches = []

for series_id in series_ids:

    print(f"Fetching matches for series {series_id}")

    url = f"https://cricbuzz-cricket.p.rapidapi.com/series/v1/{series_id}"

    response = requests.get(url, headers=HEADERS)
    data = response.json()

    for block in data.get("matchDetails", []):

        if "matchDetailsMap" not in block:
            continue

        matches = block["matchDetailsMap"].get("match", [])

        for m in matches:

            info = m.get("matchInfo", {})

            match_id = info.get("matchId")
            series_id = info.get("seriesId")
            match_desc = info.get("matchDesc")
            match_format = info.get("matchFormat")

            start_date = info.get("startDate")

            match_date = None
            year = None

            if start_date:
                dt = datetime.fromtimestamp(int(start_date) / 1000)
                match_date = dt.date()
                year = dt.year

            venue = info.get("venueInfo", {}).get("ground")
            city = info.get("venueInfo", {}).get("city")

            team1 = info.get("team1", {}).get("teamName")
            team2 = info.get("team2", {}).get("teamName")

            status = info.get("status")

            all_matches.append({
                "match_id": match_id,
                "series_id": series_id,
                "match_desc": match_desc,
                "match_format": match_format,
                "match_date": match_date,
                "year": year,
                "venue": venue,
                "venue_country": city,
                "team1": team1,
                "team2": team2,
                "status": status
            })

    time.sleep(2)

df_matches = pd.DataFrame(all_matches)

print(df_matches.head())
print("Total matches:", len(df_matches))

Fetching matches for series 3213
Fetching matches for series 3656
Fetching matches for series 4905
Fetching matches for series 6857
Fetching matches for series 7745
Fetching matches for series 9638
   match_id  series_id match_desc match_format  match_date  year  \
0     31633       3213    1st ODI          ODI  2020-11-27  2020
1     31638       3213    2nd ODI          ODI  2020-11-29  2020
2     31643       3213    3rd ODI          ODI  2020-12-02  2020
3     30540       3213   1st T20I          T20  2020-12-04  2020
4     30544       3213   2nd T20I          T20  2020-12-06  2020

                   venue venue_country      team1  team2  \
0  Sydney Cricket Ground        Sydney  AUSTRALIA  INDIA
1  Sydney Cricket Ground        Sydney  AUSTRALIA  INDIA
2            Manuka Oval      Canberra  AUSTRALIA  INDIA
3            Manuka Oval      Canberra  AUSTRALIA  INDIA
4  Sydney Cricket Ground        Sydney  AUSTRALIA  INDIA

                     status
0  Australia won by 66 runs
1  Australia won by 51 runs
2      India won by 13 runs
3      India won by 11 runs
4       India won by 6 wkts
Total matches: 47

In [119]:
import re

def parse_status(status):

    if status is None:
        return None, None, None

    status = status.lower()

    if "won by" not in status:
        return None, None, None

    winner = status.split(" won")[0].title()

    runs = None
    wickets = None

    run_match = re.search(r'(\d+) runs', status)
    wicket_match = re.search(r'(\d+) wkts?', status)

    if run_match:
        runs = int(run_match.group(1))

    if wicket_match:
        wickets = int(wicket_match.group(1))

    return winner, runs, wickets


df_matches[["match_winner","win_margin_runs","win_margin_wickets"]] = \
df_matches["status"].apply(lambda x: pd.Series(parse_status(x)))

In [120]:
df_matches.drop(columns=["status"], inplace=True)

In [121]:
df_matches[["team1","team2","match_winner","win_margin_runs","win_margin_wickets"]].head(10)

         team1    team2 match_winner  win_margin_runs  win_margin_wickets
0    AUSTRALIA    INDIA    Australia             66.0                 NaN
1    AUSTRALIA    INDIA    Australia             51.0                 NaN
2    AUSTRALIA    INDIA        India             13.0                 NaN
3    AUSTRALIA    INDIA        India             11.0                 NaN
4    AUSTRALIA    INDIA        India              NaN                 6.0
5  AUSTRALIA A  INDIA A          NaN              NaN                 NaN
6    AUSTRALIA    INDIA    Australia             12.0                 NaN
7  AUSTRALIA A    INDIA          NaN              NaN                 NaN
8    AUSTRALIA    INDIA    Australia              NaN                 8.0
9    AUSTRALIA    INDIA        India              NaN                 8.0

In [128]:
print(df_matches.columns)

Index(['match_id', 'series_id', 'match_desc', 'match_format', 'match_date',
       'year', 'venue', 'venue_country', 'team1', 'team2', 'match_winner',
       'win_margin_runs', 'win_margin_wickets'],
      dtype='str')

In [131]:
df_matches = df_matches[~df_matches['team1'].str.contains(' A', na=False)]
df_matches = df_matchesdf_matches = df_matches[
    (~df_matches['team1'].str.contains(' A', na=False)) &
    (~df_matches['team2'].str.contains(' A', na=False))
]

df_matches = df_matches.drop_duplicates()
df_matches = df_matches.reset_index(drop=True)

print("Final matches:", len(df_matches))
df_matches.head()[~df_matches['team2'].str.contains(' A', na=False)]

Final matches: 21

C:\Users\Suba\AppData\Local\Temp\ipykernel_24524\340345068.py:11: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_matches.head()[~df_matches['team2'].str.contains(' A', na=False)]

,match_id,series_id,match_desc,match_format,match_date,year,venue,venue_country,team1,team2,match_winner,win_margin_runs,win_margin_wickets
0,31633,3213,1st ODI,ODI,2020-11-27,2020,Sydney Cricket Ground,Sydney,AUSTRALIA,INDIA,Australia,66.0,NaN
1,31638,3213,2nd ODI,ODI,2020-11-29,2020,Sydney Cricket Ground,Sydney,AUSTRALIA,INDIA,Australia,51.0,NaN
2,31643,3213,3rd ODI,ODI,2020-12-02,2020,Manuka Oval,Canberra,AUSTRALIA,INDIA,India,13.0,NaN
3,30540,3213,1st T20I,T20,2020-12-04,2020,Manuka Oval,Canberra,AUSTRALIA,INDIA,India,11.0,NaN
4,30544,3213,2nd T20I,T20,2020-12-06,2020,Sydney Cricket Ground,Sydney,AUSTRALIA,INDIA,India,NaN,6.0

In [116]:
print(df_matches.columns)

Index(['match_id', 'series_id', 'match_desc', 'match_format', 'match_date',
       'year', 'venue', 'venue_country', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'match_winner', 'win_margin_runs',
       'win_margin_wickets'],
      dtype='str')

In [132]:
import psycopg2
import requests

secret = "monineha"
DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": secret,
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()
print("Connected to DB")

for _, row in df_matches.iterrows():
    cursor.execute("""
        INSERT INTO matches (
            match_id, series_id, match_desc, match_format,
            match_date, year, venue, venue_country,
            team1, team2, match_winner,
            win_margin_runs, win_margin_wickets
        )
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        ON CONFLICT (match_id) DO NOTHING
    """, tuple(row))

conn.commit()
cursor.close()
conn.close()

print("Matches inserted successfully")

Connected to DB
Matches inserted successfully

In [133]:
###

import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/30540/scard"

headers = {
	"x-rapidapi-key": "c9de7c19b5msh7ab8030188091afp1f2e9cjsn5af11208b161",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [134]:
data.keys()

dict_keys(['scorecard', 'ismatchcomplete', 'appindex', 'status', 'responselastupdated'])

In [135]:
data['scorecard']

[{'inningsid': 1,
  'batsman': [{'id': 8733,
    'balls': 40,
    'runs': 51,
    'fours': 5,
    'sixes': 1,
    'strkrate': '127.5',
    'name': 'Rahul',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': True,
    'outdec': 'c Abbott b Henriques',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1446,
    'balls': 6,
    'runs': 1,
    'fours': 0,
    'sixes': 0,
    'strkrate': '16.67',
    'name': 'Dhawan',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'b Starc',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1413,
    'balls': 9,
    'runs': 9,
    'fours': 1,
    'sixes': 0,
    'strkrate': '100',
    'name': 'Kohli',
    'nickname': '',
    'iscaptain': True,
    'iskeeper': False,
    'outdec': 'c and b Swepson',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8271,
    'balls': 15,
    'runs': 23,
    'fours': 1,
    'sixes': 1,
    'strkrate': '153.33',
    'name': 'Samson',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Swepson b Henriques',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1836,
    'balls': 8,
    'runs': 2,
    'fours': 0,
    'sixes': 0,
    'strkrate': '25',
    'name': 'Manish Pandey',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Hazlewood b Zampa',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 9647,
    'balls': 15,
    'runs': 16,
    'fours': 0,
    'sixes': 1,
    'strkrate': '106.67',
    'name': 'Hardik Pandya',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Steven Smith b Henriques',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 587,
    'balls': 23,
    'runs': 44,
    'fours': 5,
    'sixes': 1,
    'strkrate': '191.3',
    'name': 'Ravindra Jadeja',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 10945,
    'balls': 5,
    'runs': 7,
    'fours': 1,
    'sixes': 0,
    'strkrate': '140',
    'name': 'Washington Sundar',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Abbott b Starc',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 7836,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'D Chahar',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 7909,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Shami',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 10225,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'T Natarajan',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 7910,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Chahal',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''}],
  'bowler': [{'id': 7710,
    'overs': '4',
    'maidens': 0,
    'wickets': 2,
    'runs': 34,
    'economy': '8.5',
    'name': 'Starc',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 6258,
    'overs': '4',
    'maidens': 0,
    'wickets': 0,
    'runs': 39,
    'economy': '9.8',
    'name': 'Hazlewood',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8642,
    'overs': '4',
    'maidens': 0,
    'wickets': 1,
    'runs': 20,
    'economy': '5',
    'name': 'Zampa',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8136,
    'overs': '2',
    'maidens': 0,
    'wickets': 0,
    'runs': 23,
    'economy': '11.5',
    'name': 'Abbott',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 12,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 10626,
    'overs': '2',
    'maidens': 0,
    'wickets': 1,
    'runs': 21,
    'economy': '10.5',
    'name': 'Swepson',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 12,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1437,
    'overs': '4',
    'maidens': 0,
    'wickets': 3,
    'runs': 22,
    'economy': '5.5',
    'name': 'Henriques',
    'nickname': '',
    'iscaptain': False,
    'iskeeper': False,
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'dots': 0,
    'balls': 24,
    'rpb': 0.0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''}],
  'fow': {'fow': [{'batsmanid': 1446,
     'batsmanname': 'Dhawan',
     'overnbr': 2.5,
     'runs': 11,
     'ballnbr': 17},
    {'batsmanid': 1413,
     'batsmanname': 'Kohli',
     'overnbr': 6.4,
     'runs': 48,
     'ballnbr': 40},
    {'batsmanid': 8271,
     'batsmanname': 'Samson',
     'overnbr': 11.1,
     'runs': 86,
     'ballnbr': 67},
    {'batsmanid': 1836,
     'batsmanname': 'Manish Pandey',
     'overnbr': 12.4,
     'runs': 90,
     'ballnbr': 76},
    {'batsmanid': 8733,
     'batsmanname': 'Rahul',
     'overnbr': 13.5,
     'runs': 92,
     'ballnbr': 83},
    {'batsmanid': 9647,
     'batsmanname': 'Hardik Pandya',
     'overnbr': 16.5,
     'runs': 114,
     'ballnbr': 101},
    {'batsmanid': 10945,
     'batsmanname': 'Washington Sundar',
     'overnbr': 19.3,
     'runs': 152,
     'ballnbr': 117}]},
  'extras': {'legbyes': 2,
   'byes': 0,
   'wides': 5,
   'noballs': 1,
   'penalty': 0,
   'total': 8},
  'pp': {'powerplay': [{'id': 5,
     'ovrfrom': 0.1,
     'ovrto': 6.0,
     'pptype': 'Mandatory',
     'run': 42,
     'wickets': 0}]},
  'score': 161,
  'wickets': 7,
  'overs': 20.0,
  'runrate': 8.05,
  'batteamname': 'India',
  'batteamsname': 'IND',
  'isdeclared': False,
  'isfollowon': False,
  'ballnbr': 120,
  'rpb': 1.34,
  'partnership': {'partnership': [{'id': 0,
     'bat1id': 8733,
     'bat1name': 'Rahul',
     'bat1runs': 9,
     'bat1fours': 1,
     'bat1sixes': 0,
     'bat2id': 1446,
     'bat2name': 'Dhawan',
     'bat2runs': 1,
     'bat2fours': 0,
     'bat2sixes': 0,
     'totalruns': 11,
     'totalballs': 17,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 8733,
     'bat1name': 'Rahul',
     'bat1runs': 27,
     'bat1fours': 3,
     'bat1sixes': 1,
     'bat2id': 1413,
     'bat2name': 'Kohli',
     'bat2runs': 9,
     'bat2fours': 1,
     'bat2sixes': 0,
     'totalruns': 37,
     'totalballs': 23,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 8733,
     'bat1name': 'Rahul',
     'bat1runs': 14,
     'bat1fours': 1,
     'bat1sixes': 0,
     'bat2id': 8271,
     'bat2name': 'Samson',
     'bat2runs': 23,
     'bat2fours': 1,
     'bat2sixes': 1,
     'totalruns': 38,
     'totalballs': 27,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 8733,
     'bat1name': 'Rahul',
     'bat1runs': 1,
     'bat1fours': 0,
     'bat1sixes': 0,
     'bat2id': 1836,
     'bat2name': 'Manish Pandey',
     'bat2runs': 2,
     'bat2fours': 0,
     'bat2sixes': 0,
     'totalruns': 4,
     'totalballs': 9,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 8733,
     'bat1name': 'Rahul',
     'bat1runs': 0,
     'bat1fours': 0,
     'bat1sixes': 0,
     'bat2id': 9647,
     'bat2name': 'Hardik Pandya',
     'bat2runs': 1,
     'bat2fours': 0,
     'bat2sixes': 0,
     'totalruns': 2,
     'totalballs': 7,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 587,
     'bat1name': 'Jadeja',
     'bat1runs': 7,
     'bat1fours': 0,
     'bat1sixes': 0,
     'bat2id': 9647,
     'bat2name': 'Hardik Pandya',
     'bat2runs': 15,
     'bat2fours': 0,
     'bat2sixes': 1,
     'totalruns': 22,
     'totalballs': 18,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 587,
     'bat1name': 'Jadeja',
     'bat1runs': 28,
     'bat1fours': 3,
     'bat1sixes': 1,
     'bat2id': 10945,
     'bat2name': 'Washington Sundar',
     'bat2runs': 7,
     'bat2fours': 1,
     'bat2sixes': 0,
     'totalruns': 38,
     'totalballs': 17,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0},
    {'id': 0,
     'bat1id': 587,
     'bat1name': 'Jadeja',
     'bat1runs': 9,
     'bat1fours': 2,
     'bat1sixes': 0,
     'bat2id': 7836,
     'bat2name': 'Chahar',
     'bat2runs': 0,
     'bat2fours': 0,
     'bat2sixes': 0,
     'totalruns': 9,
     'totalballs': 3,
     'bat1balls': 0,
     'bat2balls': 0,
     'teamname': '',
     'teamid': 0,
     'bat1ones': 0,
     'bat1twos': 0,
     'bat1threes': 0,
     'bat1fives': 0,
     'bat1boundaries': 0,
     'bat1sixers': 0,
     'bat2ones': 0,
     'bat2twos': 0,
     'bat2threes': 0,
     'bat2fives': 0,
     'bat2boundaries': 0,
     'bat2sixers': 0}]}},
 {'inningsid': 2,
  'batsman': [{'id': 11050,
    'balls': 38,
    'runs': 34,
    'fours': 3,
    'sixes': 0,
    'strkrate': '89.47',
    'name': 'D Arcy Short',
    'nickname': 'D Arcy Short',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Hardik Pandya b T Natarajan',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1643,
    'balls': 26,
    'runs': 35,
    'fours': 5,
    'sixes': 1,
    'strkrate': '134.62',
    'name': 'Aaron Finch',
    'nickname': 'Finch',
    'iscaptain': True,
    'iskeeper': False,
    'outdec': 'c Hardik Pandya b Chahal',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 2250,
    'balls': 9,
    'runs': 12,
    'fours': 0,
    'sixes': 1,
    'strkrate': '133.33',
    'name': 'Steven Smith',
    'nickname': 'Steven Smith',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'c Samson b Chahal',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 7662,
    'balls': 3,
    'runs': 2,
    'fours': 0,
    'sixes': 0,
    'strkrate': '66.67',
    'name': 'Glenn Maxwell',
    'nickname': 'Maxwell',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'lbw b T Natarajan',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1437,
    'balls': 20,
    'runs': 30,
    'fours': 1,
    'sixes': 1,
    'strkrate': '150',
    'name': 'Moises Henriques',
    'nickname': 'Henriques',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'lbw b D Chahar',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 1649,
    'balls': 9,
    'runs': 7,
    'fours': 0,
    'sixes': 0,
    'strkrate': '77.78',
    'name': 'Matthew Wade',
    'nickname': 'Wade',
    'iscaptain': False,
    'iskeeper': True,
    'outdec': 'c Kohli b Chahal',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8136,
    'balls': 8,
    'runs': 12,
    'fours': 0,
    'sixes': 1,
    'strkrate': '150',
    'name': 'Sean Abbott',
    'nickname': 'Abbott',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 7710,
    'balls': 2,
    'runs': 1,
    'fours': 0,
    'sixes': 0,
    'strkrate': '50',
    'name': 'Mitchell Starc',
    'nickname': 'Starc',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'b T Natarajan',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 10626,
    'balls': 5,
    'runs': 12,
    'fours': 1,
    'sixes': 1,
    'strkrate': '240',
    'name': 'Mitchell Swepson',
    'nickname': 'Swepson',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': 'not out',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 8642,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,
    'strkrate': '0',
    'name': 'Adam Zampa',
    'nickname': 'Zampa',
    'iscaptain': False,
    'iskeeper': False,
    'outdec': '',
    'videotype': '',
    'videourl': '',
    'videoid': 0,
    'planid': 0,
    'imageid': 0,
    'premiumvideourl': '',
    'iscbplusfree': False,
    'ispremiumfree': False,
    'inmatchchange': '',
    'isoverseas': False,
    'playingxichange': ''},
   {'id': 6258,
    'balls': 0,
    'runs': 0,
    'fours': 0,
    'sixes': 0,

In [191]:
import requests
import json
import os
import time

# API details
url_template = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{}/scard"
headers = {
    "x-rapidapi-key": "c9de7c19b5msh7ab8030188091afp1f2e9cjsn5af11208b161",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# List of match IDs
match_ids = [30540, 30544, 30545, 30554, 30555, 31633, 31638, 31643, 31647, 31648, 
             56955, 56962, 56964, 56969, 56976, 91778, 91787, 91796, 91805, 91814, 108903]

# Folder to save JSON files
os.makedirs("matches_json", exist_ok=True)

for match_id in match_ids:
    print(f"Fetching match {match_id} ...")
    response = requests.get(url_template.format(match_id), headers=headers)
    if response.status_code == 200:
        data = response.json()
        with open(f"matches_json/match_{match_id}.json", "w") as f:
            json.dump(data, f)
        print(f"Saved match_{match_id}.json")
    else:
        print(f"Error fetching match {match_id}: {response.status_code}")
    
    time.sleep(1)  # pause 1 sec to avoid rate limit

Fetching match 30540 ...
Saved match_30540.json
Fetching match 30544 ...
Saved match_30544.json
Fetching match 30545 ...
Saved match_30545.json
Fetching match 30554 ...
Saved match_30554.json
Fetching match 30555 ...
Saved match_30555.json
Fetching match 31633 ...
Saved match_31633.json
Fetching match 31638 ...
Saved match_31638.json
Fetching match 31643 ...
Saved match_31643.json
Fetching match 31647 ...
Saved match_31647.json
Fetching match 31648 ...
Saved match_31648.json
Fetching match 56955 ...
Saved match_56955.json
Fetching match 56962 ...
Saved match_56962.json
Fetching match 56964 ...
Saved match_56964.json
Fetching match 56969 ...
Saved match_56969.json
Fetching match 56976 ...
Saved match_56976.json
Fetching match 91778 ...
Saved match_91778.json
Fetching match 91787 ...
Saved match_91787.json
Fetching match 91796 ...
Saved match_91796.json
Fetching match 91805 ...
Saved match_91805.json
Fetching match 91814 ...
Saved match_91814.json
Fetching match 108903 ...
Saved match_108903.json

In [196]:
import requests
import json

# API details
url_template = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{}/scard"
headers = {
    "x-rapidapi-key": "88ec27ace6msh2cd1b0b9df1b85ap14d3d0jsna6d875c38e92",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

match_ids = [30540, 30544, 30545, 30554, 30555, 31633, 31638, 31643, 31647, 31648, 
             56955, 56962, 56964, 56969, 56976, 91778, 91787, 91796, 91805, 91814, 108903]

for match_id in match_ids:
    response = requests.get(url_template.format(match_id), headers=headers)
    if response.status_code != 200:
        print(f"Failed to fetch match {match_id}, status: {response.status_code}")
        continue
    
    data = response.json()
    
    # Check structure
    if 'scorecard' not in data or not data['scorecard']:
        print(f"Match {match_id} has no scorecard / innings, skipping...")
    else:
        innings_count = len(data['scorecard'])
        print(f"Match {match_id} has {innings_count} innings available.")

Match 30540 has 2 innings available.
Match 30544 has 2 innings available.
Match 30545 has 2 innings available.
Match 30554 has 4 innings available.
Match 30555 has 4 innings available.
Match 31633 has 2 innings available.
Match 31638 has 2 innings available.
Match 31643 has 2 innings available.
Match 31647 has 4 innings available.
Match 31648 has 4 innings available.
Match 56955 has 2 innings available.
Match 56962 has 2 innings available.
Match 56964 has 2 innings available.
Match 56969 has 4 innings available.
Match 56976 has 4 innings available.
Match 91778 has 4 innings available.
Match 91787 has 4 innings available.
Match 91796 has 4 innings available.
Match 91805 has 4 innings available.
Match 91814 has 4 innings available.
Match 108903 has 2 innings available.

In [199]:
import json
import os
import pandas as pd

match_ids = [30540, 30544, 30545, 30554, 30555, 31633, 31638, 31643, 31647, 31648, 
             56955, 56962, 56964, 56969, 56976, 91778, 91787, 91796, 91805, 91814, 108903]

batsmen_rows = []
bowlers_rows = []
partnership_rows = []

for match_id in match_ids:
    filepath = f"matches_json/match_{match_id}.json"
    if not os.path.exists(filepath):
        print(f"File missing for match {match_id}, skipping...")
        continue

    with open(filepath) as f:
        match = json.load(f)

    if 'scorecard' not in match:
        continue

    for innings in match['scorecard']:
        innings_id = innings['inningsid']
        team = innings['batteamname']

        # Extras & total wickets
        extras = innings.get('extras', {})
        total_wickets = innings.get('wickets', 0)

        # Batsmen
        for b in innings.get('batsman', []):
            batsmen_rows.append({
                "match_id": match_id,
                "innings_id": innings_id,
                "team": team,
                "batsman_id": b.get('id'),
                "batsman_name": b.get('name'),
                "runs": b.get('runs', 0),
                "balls": b.get('balls', 0),
                "fours": b.get('fours', 0),
                "sixes": b.get('sixes', 0),
                "strike_rate": float(b.get('strkrate', 0)),
                "out_decision": b.get('outdec', ''),
                "byes": extras.get('byes', 0),
                "legbyes": extras.get('legbyes', 0),
                "wides": extras.get('wides', 0),
                "noballs": extras.get('noballs', 0),
                "penalty": extras.get('penalty', 0),
                "total_extras": extras.get('total', 0),
                "total_wickets": total_wickets
            })

        # Bowlers
        for bw in innings.get('bowler', []):
            bowlers_rows.append({
                "match_id": match_id,
                "innings_id": innings_id,
                "team": team,
                "bowler_id": bw.get('id'),
                "bowler_name": bw.get('name'),
                "overs": bw.get('overs', 0),
                "maidens": bw.get('maidens', 0),
                "runs": bw.get('runs', 0),
                "wickets": bw.get('wickets', 0),
                "economy": float(bw.get('economy', 0))
            })

        # Partnerships
        if 'partnership' in innings and 'partnership' in innings['partnership']:
            for p in innings['partnership']['partnership']:
                partnership_rows.append({
                    "match_id": match_id,
                    "innings_id": innings_id,
                    "bat1_id": p.get('bat1id'),
                    "bat1_name": p.get('bat1name'),
                    "bat2_id": p.get('bat2id'),
                    "bat2_name": p.get('bat2name'),
                    "total_runs": p.get('totalruns', 0),
                    "total_balls": p.get('totalballs', 0)
                })

# Create DataFrames
df_batsmen = pd.DataFrame(batsmen_rows)
df_bowlers = pd.DataFrame(bowlers_rows)
df_partnerships = pd.DataFrame(partnership_rows)

print("Batsmen Sample:")
print(df_batsmen.head())

print("\nBowlers Sample:")
print(df_bowlers.head())

print("\nPartnerships Sample:")
print(df_partnerships.head())

Batsmen Sample:
   match_id  innings_id   team  batsman_id   batsman_name  runs  balls  fours  \
0     30540           1  India        8733          Rahul    51     40      5
1     30540           1  India        1446         Dhawan     1      6      0
2     30540           1  India        1413          Kohli     9      9      1
3     30540           1  India        8271         Samson    23     15      1
4     30540           1  India        1836  Manish Pandey     2      8      0

   sixes  strike_rate           out_decision  byes  legbyes  wides  noballs  \
0      1       127.50   c Abbott b Henriques     0        2      5        1
1      0        16.67                b Starc     0        2      5        1
2      0       100.00        c and b Swepson     0        2      5        1
3      1       153.33  c Swepson b Henriques     0        2      5        1
4      0        25.00    c Hazlewood b Zampa     0        2      5        1

   penalty  total_extras  total_wickets
0        0             8              7
1        0             8              7
2        0             8              7
3        0             8              7
4        0             8              7

Bowlers Sample:
   match_id  innings_id   team  bowler_id bowler_name overs  maidens  runs  \
0     30540           1  India       7710       Starc     4        0    34
1     30540           1  India       6258   Hazlewood     4        0    39
2     30540           1  India       8642       Zampa     4        0    20
3     30540           1  India       8136      Abbott     2        0    23
4     30540           1  India      10626     Swepson     2        0    21

   wickets  economy
0        2      8.5
1        0      9.8
2        1      5.0
3        0     11.5
4        1     10.5

Partnerships Sample:
   match_id  innings_id  bat1_id bat1_name  bat2_id      bat2_name  \
0     30540           1     8733     Rahul     1446         Dhawan
1     30540           1     8733     Rahul     1413          Kohli
2     30540           1     8733     Rahul     8271         Samson
3     30540           1     8733     Rahul     1836  Manish Pandey
4     30540           1     8733     Rahul     9647  Hardik Pandya

   total_runs  total_balls
0          11           17
1          37           23
2          38           27
3           4            9
4           2            7

In [200]:
import psycopg2

DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": "monineha",
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()

# Insert batsmen
for i, row in df_batsmen.iterrows():
    cursor.execute("""
        INSERT INTO batsmen VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

# Insert bowlers
for i, row in df_bowlers.iterrows():
    cursor.execute("""
        INSERT INTO bowlers VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

# Insert partnerships
for i, row in df_partnerships.iterrows():
    cursor.execute("""
        INSERT INTO partnerships VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
cursor.close()
conn.close()
print("Data inserted successfully!")

Data inserted successfully!

In [ ]:
## toss


import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/30540/leanback"

headers = {
	"x-rapidapi-key": "88ec27ace6msh2cd1b0b9df1b85ap14d3d0jsna6d875c38e92",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

data = response.json()

In [20]:
data.keys()

dict_keys(['miniscore', 'matchheaders'])

In [21]:
data['matchheaders']

{'state': 'Complete',
 'status': 'India won by 11 runs',
 'matchformat': 'T20',
 'matchstarttimestamp': 1607069400000,
 'teamdetails': {'batteamid': 4,
  'batteamname': 'AUS',
  'bowlteamid': 2,
  'bowlteamname': 'IND'},
 'momplayers': {'player': [{'id': '7910',
    'name': 'Yuzvendra Chahal',
    'captain': False,
    'role': 'Batsman',
    'keeper': False,
    'teamname': '',
    'isheader': False,
    'imageId': 0,
    'battingStyle': '',
    'bowlingStyle': '',
    'faceimageid': 170690,
    'countryimageid': 0,
    'playingxichange': '',
    'inmatchchange': '',
    'isoverseas': False}],
  'category': ''},
 'mosplayers': {'player': [], 'category': ''},
 'winningteamid': 2,
 'revisedtarget': 0,
 'matchendtimestamp': 1607082000000,
 'seriesid': 3213,
 'matchdesc': '1st T20I',
 'seriesname': 'India tour of Australia, 2020-21',
 'alerttype': '',
 'tossresults': {'tosswinnerid': 0, 'tosswinnername': '', 'decision': ''},
 'livestreamenabled': False,
 'team1': {'teamid': 4,
  'teamname': 'Australia',
  'teamsname': 'AUS',
  'isfullmember': False,
  'isassociated': False,
  'isleagueteam': False,
  'iswomenteam': False,
  'isheader': False,
  'isactive': False,
  'teampriority': '',
  'isvideopresent': False,
  'imageid': 0,
  'countryname': '',
  'belongsto': '',
  'teamcolor': ''},
 'team2': {'teamid': 2,
  'teamname': 'India',
  'teamsname': 'IND',
  'isfullmember': False,
  'isassociated': False,
  'isleagueteam': False,
  'iswomenteam': False,
  'isheader': False,
  'isactive': False,
  'teampriority': '',
  'isvideopresent': False,
  'imageid': 0,
  'countryname': '',
  'belongsto': '',
  'teamcolor': ''}}

In [9]:
import psycopg2

DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": "monineha",
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()

# List all columns for a table, e.g., batsmen
cursor.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'batsmen';
""")
columns = cursor.fetchall()
print("Batsmen table structure:")
for col in columns:
    print(col)

conn.close()

Batsmen table structure:
('match_id',)
('innings_id',)
('team',)
('batsman_id',)
('batsman_name',)
('runs',)
('balls',)
('fours',)
('sixes',)
('strike_rate',)
('out_decision',)
('byes',)
('legbyes',)
('wides',)
('noballs',)
('penalty',)
('total_extras',)
('total_wickets',)

In [10]:
import psycopg2

DB_CONFIG = {
    "dbname": "cricbuzz",
    "user": "postgres",
    "password": "monineha",
    "host": "localhost",
    "port": 5432
}

conn = psycopg2.connect(**DB_CONFIG)
cursor = conn.cursor()

# List all columns for a table, e.g., matches
cursor.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'matches';
""")
columns = cursor.fetchall()
print("matches table structure:")
for col in columns:
    print(col)

matches table structure:
('match_id',)
('series_id',)
('match_desc',)
('match_format',)
('match_date',)
('year',)
('venue',)
('venue_country',)
('team1',)
('team2',)
('match_winner',)
('win_margin_runs',)
('win_margin_wickets',)

In [ ]:

cursor.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'partnerships';
""")
columns = cursor.fetchall()
print("Partnerships table structure:")
for col in columns:
    print(col)

Partnerships table structure:
('match_id',)
('innings_id',)
('bat1_id',)
('bat1_name',)
('bat2_id',)
('bat2_name',)
('total_runs',)
('total_balls',)

In [11]:
# Repeat for bowlers
cursor.execute("""
    SELECT column_name
    FROM information_schema.columns
    WHERE table_name = 'bowlers';
""")
columns = cursor.fetchall()
print("Bowlers table structure:")
for col in columns:
    print(col)

conn.close()

Bowlers table structure:
('match_id',)
('innings_id',)
('team',)
('bowler_id',)
('bowler_name',)
('overs',)
('maidens',)
('runs',)
('wickets',)
('economy',)